---
format: gfm
default-image-extension: ""
editor: 
  markdown: 
    wrap: 72
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# Spherical harmonic analysis of faceted spheroids identifies shaping strategies and standardisation at Qianshangying (North China)


This repository contains the data and code for our paper:

> Ye Zhi, Ben Marwick, Li Hao, Shuwen Pei (2025). Spherical harmonic
> analysis of faceted spheroids identifies shaping strategies and
> standardisation at Qianshangying (North China)". Submitted to *Journal
> of Archaeological Science*

<!-- A pre-print of this paper is freely available on SocArXiv:
https://osf.io/preprints/socarxiv/ -->

## Contents

The **analysis** directory contains:

-   [:file_folder: paper](/analysis/paper): Quarto source document for
    manuscript. Includes code to reproduce the figures and tables
    generated by the analysis.
-   [:file_folder: data](/analysis/data): Data used in the analysis.
-   [:file_folder: figures](/analysis/paper/figures): Plots and other
    illustrations

The **py_SPHARM** directory contains:

-   [:file_folder: py_SPHARM](/py_SPHARM): Python source files for
    SPHARM analysis.
    -   **SPHARM_main**:
        -   `batch_operation.py` — batch calculation of spherical
            harmonics for STL files.\
        -   `main.py` — shape analysis using spherical harmonics for a
            single STL file, including visualization of analysis
            results.\
    -   **SPHARM_modules**: supporting modules for main scripts,
        including shape preprocessing, spherical harmonic
        computation/statistics, shape reconstruction, and
        computation/output of sphericity and curvature.

# How to download and run locally

For this first part of the workflow that uses Python, we used [conda](https://www.anaconda.com/), an open-source,  cross-platform package and environment manager that installs software packages and manages isolated environments to preventing dependency conflicts between projects. You will need to install this to follow these instructions. We developed the project in a Linux environment on Ubuntu via Windows' WSL. 

Start by downloading a copy of this repository with the Python and R code files, then...

1. **Download STL files**

Go to the [OSF repository](https://osf.io/ctne9/files/osfstorage) and download the folder containing STL models: `3d_models_QSY_spheroids_multi_poly`  
   
2. **Unzip and place STL files in project directory** 

Extract the downloaded archive. After unzipping, copy the entire folder **`3d_models_QSY_spheroids_multi_poly`** into this directory:  `/py_SPHARM/SPHARM_main`  
   
3. **Create a new Python environment** 

```
cd py_SPHARM
conda env create -f environment.yml --solver=libmamba
conda activate spharm
```

Move to the directory in the repository that has the Python code, open a terminal window, and create a new Python environment for this project to avoid conflicts with Python packages you may already have, then we will activate this new environment, and install the required packages

4. **Run the batch operation script**

```
python -m SPHARM_main."batch operation"
```

This script will process all STL files in the folder `3d_models_QSY_spheroids_multi_poly` and perform the following computations:    
     - SPHARM (spherical harmonics) calculation for each model    
     - Rotation-invariant spectrum computation    
     - Spherical harmonic energy (SHE) calculation    
     - UMAP analysis on the rotation-invariant spectrum   

You can replace the input folder with your own STL files to perform a similar analysis. We also include `main.py` to process one 3D model at time. By default, all output results will be saved to `/analysis/data/raw_data/SPHARM_sphericity_curvature_result`    
   
   
6. **Run the curvature script**    

```
python SPHARM_modules/curvature.py
```
This script will compute the curvature for all STL files in the folder `3d_models_QSY_spheroids_multi_poly`. By default, all output results will be saved to `/analysis/data/raw_data/SPHARM_sphericity_curvature_result`  
   
   
7. **Run the sphericity script**   

```
python SPHARM_modules/sphericity.py
```
    
This script will compute the sphericity for all STL files in the folder `3d_models_QSY_spheroids_multi_poly`. By default, all output results will be saved to `/analysis/data/raw_data/SPHARM_sphericity_curvature_result`
   
That completes the part of the workflow that analyses the 3D shapes using Python. The next steps compute statistical analysis of the spherical harmonics and other attributes of the artefacts using R v4.4.  

8. **Data processing and visualization in R**  

Our manuscript is a Quarto document that contains the text of our paper interwoven with blocks of R code that generates the data visualizations and tables. To execute all the code and generate a docx document showing the results, run this line in the terminal, assuming you are continuing directly from the previous steps:

```
cd .. # to get back to the top level of the project
R -e "renv::restore()" # installed required R pkgs
quarto render analysis/paper/paper.qmd --to docx
```

Alternatively, you can open the `.Rproj` file in RStudio, run `renv::restore()` to install the necessary packages, and then open `analysis/paper/paper.qmd` in RStudio and render it to produce `paper.docx`, or run the R code interactively.   
   
## How to download and run locally in a Docker container

This research compendium includes a [Dockerfile](Dockerfile) that
specifies the computational environment used to generate the results
presented in the paper. You can recreate this environment, which
includes R, RStudio and all necessary R packages, on your computer by
following these steps:

1.  Install [Docker](https://www.docker.com/get-started/) on your computer   

2.  Download the compendium, e.g. from GitHub by clicking on the green `< > Code` button above, then click `Download ZIP`, then unzip on your computer    

3.  Set your terminal working directory to the compendium, and run (be sure to include the period):

```
docker build -t spharm .
``` 

 to build the container on your computer, it will take a few minutes and require a fast internet connection.
 
4.  Run in your terminal (linux and OSX):

```
docker run -d -p 8787:8787 -v $(pwd):/project  -w /project -e PASSWORD=rstudio spharm
```

For Windows:

```
MSYS_NO_PATHCONV=1 docker run -d -p 8787:8787 -v $(pwd):/project -w /project -e PASSWORD=rstudio spharm
```

to start the container on your computer
 
5.  Go to <http://localhost:8787/> with your browser and enter `rstudio` in both fields to start RStudio in your browser
    
6.  In RStudio, open this README file and follow the steps above in the section 'How to download and run locally'. You can run `rmarkdown::render("analysis/paper/paper.qmd", output_dir='/tmp')` to render the Quarto document that is the manuscript submitted for publication

8.  After the code has executed, view the rendered output document by running `browseURL("/tmp/paper.docx")`

9.  When finished, to delete all the Docker containers from your computer, run this in the terminal on your desktop:  `docker ps -aq | xargs docker stop | xargs docker rm`

### Licenses

**Text and figures :**
[CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)

**Code :** See the [DESCRIPTION](DESCRIPTION) file

**Data :** [CC-0](http://creativecommons.org/publicdomain/zero/1.0/)
attribution requested in reuse
