<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-07-10">
<meta name="keywords" content="<p>keyword 1; keyword 2; keyword 3</p>">

<title>Shaping strategies and standardisation of faceted spheroids from Qianshangying (North China)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="paper_files/libs/quarto-html/quarto.js"></script>
<script src="paper_files/libs/quarto-html/popper.min.js"></script>
<script src="paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="paper_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="paper_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Shaping strategies and standardisation of faceted spheroids from Qianshangying (North China)</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 10, 2025</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Text of abstract</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p></p><p>keyword 1; keyword 2; keyword 3</p><p></p>
  </div>
</div>

</header>


<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->
<!-- With the following code you can access and display values from the yml header above. -->
<p>Keywords: keyword 1; keyword 2; keyword 3</p>
<p>Highlights: These are the highlights.</p>
<!-- The actual document text starts here: -->
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Spheroids are a widely distributed type of stone artifact, appearing across a broad temporal and geographic range—from the Oldowan and Acheulean to the Middle Paleolithic—and in diverse archaeological assemblages.<span class="citation" data-cites="willoughby1985 Cabanes2024">(<a href="#ref-willoughby1985" role="doc-biblioref">Willoughby 1985</a>; <a href="#ref-Cabanes2024" role="doc-biblioref">Cabanès et al. 2024</a>)</span>.</p>
<p>Early descriptions of spheroids were provided by <span class="citation" data-cites="clark1955">(<a href="#ref-clark1955" role="doc-biblioref">Clark 1955</a>)</span> and <span class="citation" data-cites="kleindienst1962">(<a href="#ref-kleindienst1962" role="doc-biblioref">Kleindienst 1962</a>)</span>, and <span class="citation" data-cites="leakey1971">(<a href="#ref-leakey1971" role="doc-biblioref">Leakey 1971</a>)</span> later formally introduced the term spheroid, alongside polyhedron and bola, in his classification of the Developed Oldowan. Leakey’s definition of spheroids remains a widely cited typological standard: spheroids are rounded lithic objects whose entire surface is covered with flake scars, while subspheroids are generally less symmetrical and may retain portions of the original cortex. Compared to spheroids, polyhedrons are characterized by multiple intersecting flake removals, producing a distinctly angular morphology; bolas exhibit smoother and more rounded surfaces with no visible crests <span class="citation" data-cites="leakey1971 tittonSubspheroidsLithicAssemblage2020 deweyer2017">(<a href="#ref-leakey1971" role="doc-biblioref">Leakey 1971</a>; <a href="#ref-tittonSubspheroidsLithicAssemblage2020" role="doc-biblioref">Titton et al. 2020</a>; <a href="#ref-deweyer2017" role="doc-biblioref">De Weyer 2017</a>)</span>.</p>
<p>Although these artifact types are frequently grouped under the category “PSB” of Polyhedron, Spheroid and Bolas (or “PSSB” when subspheroids are included) and are commonly interpreted as volumetrically reduced artifacts organized around a central point, this morphology-based classification has led to several interpretive challenges. Artifacts identified as spheroids in one study may be classified as bolas or attributed to entirely different technological categories in another. Furthermore, research has shown that these forms may not represent a unified <em>chaîne opératoire</em> : differences in raw material selection suggest divergent technological strategies and potentially distinct functional purposes <span class="citation" data-cites="deweyer2017 jones1994">(<a href="#ref-deweyer2017" role="doc-biblioref">De Weyer 2017</a>; <a href="#ref-jones1994" role="doc-biblioref">Jones et al. 1994</a>)</span>.</p>
<p>At present, the technological category and function of spheroids remain central topics of debate. Broadly, spheroids have been interpreted as hammerstones <span class="citation" data-cites="mussi2025 schick1994">(<a href="#ref-mussi2025" role="doc-biblioref">Mussi 2025</a>; <a href="#ref-schick1994" role="doc-biblioref">Schick and Toth 1994</a>)</span>, cores <span class="citation" data-cites="sahnouni1997">(<a href="#ref-sahnouni1997" role="doc-biblioref">Sahnouni, Schick, and Toth 1997</a>)</span>, or projectiles <span class="citation" data-cites="leakey1979">(<a href="#ref-leakey1979" role="doc-biblioref">Leakey 1979</a>)</span>. Closely tied to this debate is the question of their production strategy, which remains unclear. Experimental replication and site-specific diacritical analyses have produced divergent interpretations. One view suggests that spheroids emerged unintentionally as the by-products of core exhaustion, which represents a low-effort strategy aimed at flake production <span class="citation" data-cites="sahnouni1997">(<a href="#ref-sahnouni1997" role="doc-biblioref">Sahnouni, Schick, and Toth 1997</a>)</span>. Another perspective holds that spheroids were naturally produced through high-intensity battering <span class="citation" data-cites="schick1994">(<a href="#ref-schick1994" role="doc-biblioref">Schick and Toth 1994</a>)</span>; [@mora2005]; <span class="citation" data-cites="clark1955">(<a href="#ref-clark1955" role="doc-biblioref">Clark 1955</a>)</span>. In contrast, a third view proposes that spheroids reflect a conceptual template and were produced through a deliberate shaping strategy <span class="citation" data-cites="tittonSubspheroidsLithicAssemblage2020 Muller2023 texier2014">(<a href="#ref-tittonSubspheroidsLithicAssemblage2020" role="doc-biblioref">Titton et al. 2020</a>; <a href="#ref-Muller2023" role="doc-biblioref">Muller et al. 2023</a>; <a href="#ref-texier2014" role="doc-biblioref">Texier and Roche 2014</a>)</span>. [BM: yes, this is great, good job, this is a very important paragraph for the introduction of the paper. We might need to expand it a bit]</p>
<p>Rather than reflecting a single functional or technological model, these varying interpretations may instead capture regional variability shaped by differences in raw materials, morphologies, and reduction strategies. As <span class="citation" data-cites="Cabanes2024">(<a href="#ref-Cabanes2024" role="doc-biblioref">Cabanès et al. 2024</a>)</span> said, spheroids may not represent a homogenous category. [BM: you have already mentioned debates in the previous paragraph, so it’s seems a bit odd to mention debates again here without continuity with the previous paragraph. Maybe these two sentences are better as the opening sentences for the paper, setting the scene for more information about the debates] This highlights the need to move beyond generalized typological categories and instead engage more directly with local contexts and specific assemblages. Site-specific studies are therefore essential for reconstructing the spatial and temporal distribution of spheroids, as well as for identifying their distinct technological traits and functions.</p>
<p>In this study, we analyzed material from the Middle Pleistocene Qianshangying site (QSY) in northern China. Among an assemblage previously classified as a simple core-flake industry, we identified a group of highly standardized spheroids and subspheroids. we observed notable differences between these artifacts and multifacial cores or polyhedrons, which are stone artifacts through typical flaking strategies. Our goal was to evaluate whether these spheroids exhibited standardized morphology and production patterns, and whether their tendency toward spherical form resulted from deliberate and systematic reduction processes. based on the results, further to answer the question of whether the concept and manufacture of these spheroids represent a distinct technological tradition, separate from conventional flake-based strategies.</p>
<p>We conducted quantitative morphological and technological analyses of the spheroids recovered from the Qianshangying (QSY) site, including the novel application of spherical harmonic analysis to a Paleolithic assemblage from East Asia. These analyses help clarify the technological strategy behind spheroid production at QSY, within the broader context of Middle Pleistocene lithic practices in northern China.</p>
</section>
<section id="context-of-qsy-and-its-spheroids" class="level1">
<h1>Context of QSY and its spheroids</h1>
<div class="cell">
<div class="cell-output-display">
<div id="fig-QSY-geography-chronology" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-QSY-geography-chronology-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/QSY_geography_chronology.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-QSY-geography-chronology-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Geological Context and Chrono-Stratigraphy of the QSY Site)
</figcaption>
</figure>
</div>
</div>
</div>
<p>QSY lies in the Nihewan Basin, a region in northern China situated between the Chinese Loess Plateau and the Inner Mongolian Plateau. The basin preserves extensive Quaternary fluvio-lacustrine and loess deposits <span class="citation" data-cites="li2000 yuan2009">(<a href="#ref-li2000" role="doc-biblioref">R. Li et al. 2000</a>; <a href="#ref-yuan2009" role="doc-biblioref">Yuan et al. 2009</a>)</span>, hosts the highest concentrations of Pleistocene Paleolithic sites in East Asia, and is especially significant for preserving evidence of early hominin activities outside Africa dating back over one million years <span class="citation" data-cites="yang2020 yang2017 pei2019 pei2017 zhu2001 zhu2004">(<a href="#ref-yang2020" role="doc-biblioref">Yang et al. 2020</a>, <a href="#ref-yang2017" role="doc-biblioref">2017</a>; <a href="#ref-pei2019" role="doc-biblioref">Pei et al. 2019</a>, <a href="#ref-pei2017" role="doc-biblioref">2017</a>; <a href="#ref-zhu2001" role="doc-biblioref">Zhu et al. 2001</a>, <a href="#ref-zhu2004" role="doc-biblioref">2004</a>)</span>. In recent years, nearly 20 Middle Pleistocene sites—including Jijiazhuang and Caijiagou—have been identified in the southeastern part of the basin <span class="citation" data-cites="yuwei2023 ye2024">(<a href="#ref-yuwei2023" role="doc-biblioref">Yuwei et al. 2023</a>; <a href="#ref-ye2024" role="doc-biblioref">Ye et al. 2024</a>)</span>, within the Yuxian Sub-basin, thereby completing the regional cultural sequence of the Nihewan Basin (<a href="#fig-QSY-geography-chronology" class="quarto-xref">Figure&nbsp;1</a>).</p>
<p>The QSY site complex consists of four localities from QSY-A to QSY-D, discovered in 2015. It is among the region’s most artifact-rich archaeological site. Geomorphological and sedimentological evidence indicates that the stratigraphy at the site records a full cycle of lake expansion, retreat, re-expansion, and eventually disappearance of the ancient Nihewan lake, and hominin occupation occurred in a marginal lacustrine setting during a low lake-level episode [BM: citation needed]. The stratigraphic context of QSY indicates a short-term occupation resulting from a single hominin activity event. The assemblage appears to be largely in situ, exhibiting minimal disturbance after deposition and well-preserved patterns of technological combination. ESR dating of the cultural layer places hominin activity at approximately 429 ± 39 ka [BM: citation needed].</p>
<p>A total of 955 stone artifacts were recovered from four localities at the QSY site. Following a widely used techno-typological framework [<span class="citation" data-cites="Isaac1981">G. L. Isaac (<a href="#ref-Isaac1981" role="doc-biblioref">1981</a>)</span>; <span class="citation" data-cites="Isaac1986">G. L. Isaac (<a href="#ref-Isaac1986" role="doc-biblioref">1986</a>)</span>; <span class="citation" data-cites="delatorre2004">De La Torre (<a href="#ref-delatorre2004" role="doc-biblioref">2004</a>)</span>; <span class="citation" data-cites="de2018oldowan">Torre and Mora (<a href="#ref-de2018oldowan" role="doc-biblioref">2018</a>)</span>; @pei2017], the assemblage was classified into four general categories: flaked pieces (n = 247, 26.0%), detached pieces (n = 686, 71.8%), pounded pieces (n = 4, 0.4%), and unmodified materials (n = 17, 1.8%). [BM: is it possible to use inline R code for these numbers?] Among these, 12 spheroids and subspheroids were identified, accounting for 1.3% of the total lithic assemblage.</p>
<p>Raw materials at QSY were classified into four categories following <span class="citation" data-cites="pei2002">Pei and Hou (<a href="#ref-pei2002" role="doc-biblioref">2002</a>)</span> and <span class="citation" data-cites="pei2017">Pei et al. (<a href="#ref-pei2017" role="doc-biblioref">2017</a>)</span>: lava, siliceous dolomite, chert, and others. Lava rock dominates the assemblage (n=637, 66.7%), followed by siliceous dolomite (n=209, 21.9%), with chert and other materials comprising the remainder (n=53, 5.5% and n=56, 5.9% respectively). It seems that spheroids show no strong raw material preference. Of the 12 identified spheroids, 75.0% are lava (n = 9), 16.7% are siliceous dolomite (n = 2), and 8.3% is quartzite (n=1, classified under “other”), roughly mirroring the assemblage’s overall composition except for the absence of chert. However, when compared to cores, which are 66.0% lava (n = 62), 22.3% siliceous dolomite (n = 21), 4.3% chert (n = 4), and 7.4% other (n = 7), spheroids show a higher frequency of lava use, suggesting the different preferences in raw material selection for the spheroids and the cores. (pie chart in need?)</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-core-spheroid-size" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-core-spheroid-size-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="paper_files/figure-html/fig-core-spheroid-size-1.png" class="img-fluid figure-img" width="4200">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-core-spheroid-size-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: box plot showing size of cores and spheroids
</figcaption>
</figure>
</div>
</div>
</div>
<p>In terms of dimensions, the average length, width, thickness, and weight of spheroids were 82.9 mm (SD = 37.3), 70.1 mm (SD = 24.4), 61.2 mm (SD = 22), and 634.4 g (SD = 758.9), respectively, as shown in <a href="#fig-core-spheroid-size" class="quarto-xref">Figure&nbsp;2</a>. Two spheroids showed outlier values in size, being either unusually large or small, while the rest exhibited relatively concentrated size distributions. In contrast, cores displayed greater variability in size, with standard deviations of 29.8 mm, 24.2 mm, and 20.3 mm for length, width, and thickness, respectively. The polyhedrons and multifacial cores showed less variation than the overall core group, but their dimensional variability remained substantially greater than that of the spheroids.Additionally, spheroids tend to have similar values across length, width, and thickness, reflecting their overall symmetry. In contrast, cores, including polyhedrons and multifacial cores show marked differences among these dimensions, indicating more irregular and elongated forms.</p>
</section>
<section id="method" class="level1">
<h1>Method</h1>
<p>In this study, the 3d models of the cores were collected and used for morphometric and technological analysis. Digital data were captured using Artec Spider, and post-processing was carried out with Artec Studio [version number]. The 3D scan files and all the R and Python code used in the analyses reported here are openly available online at https://doi.org/xxxx/xxxx/./xxxx/.</p>
<section id="morphometric-analysis" class="level2">
<h2 class="anchored" data-anchor-id="morphometric-analysis">Morphometric Analysis</h2>
<p>Based on typological study, we identify some faceted sub-spheroids/spheroids in QSY site. To minimize subjective judgment inherent in typological classifications—particularly in distinguishing spheroids from stone cores—we applied quantitative methods to evaluate the degree of difference between the archaeological spheroids and a perfect sphere. In addition to the spheroids, we included other multifacial cores and polyhedrons in the morphological study to explore whether they can be distinguished from the spheroids.</p>
<p>These quantitative methods included computing the sphericity index, 3D spherical harmonics, spherical harmonic energy (SHE) and the centroid offset for each artifact. We also examined the degree of standardization of the spheroids by compulating coefficients of variation <span class="citation" data-cites="Eerkens2001 muller2023">(<a href="#ref-Eerkens2001" role="doc-biblioref">Eerkens and Bettinger 2001</a>; <a href="#ref-muller2023" role="doc-biblioref">Muller and Clarkson 2023</a>)</span> of shape proxies. Furthermore, we compared the results of the typological and our new morphometric analyses to investigate the validity of the traditional typological approach.</p>
<section id="sphericity-index" class="level3">
<h3 class="anchored" data-anchor-id="sphericity-index">Sphericity index</h3>
<p>To evaluate the degree to which the artifacts approximate a perfect sphere, this study employs a standardized sphericity index originally proposed by <span class="citation" data-cites="Wadell1935">Wadell (<a href="#ref-Wadell1935" role="doc-biblioref">1935</a>)</span> and later adapted for 3D digital models in geoscientific research. The index is calculated using the following formula:</p>
<p><span class="math display">\[
\Psi = \frac{\pi^{1/3} (6V)^{2/3}}{A}
\]</span></p>
<p>Where V is the volume and A is the surface area of the object. This dimensionless metric yields a maximum value of 1 for a perfect sphere. While values closer to 1 generally indicate a more spherical geometry, sphericity is calculated solely from volume and surface area. As a result, some irregular objects may exhibit high sphericity, while conversely, objects that are generally spherical in shape may deviate from ideal sphericity due to angular features or surface roughness. Thus, sphericity serves as a useful but limited proxy for assessing how close an object is to a perfect sphere. We used Python to derive surface area and volume measurements from 3D mesh models, and before that all models were decimated to a consistent face count and subjected to unit normalization to ensure comparability across artifacts.</p>
</section>
<section id="d-spherical-harmonics-analysis" class="level3">
<h3 class="anchored" data-anchor-id="d-spherical-harmonics-analysis">3D spherical harmonics analysis</h3>
<p>Spherical Harmonic (SPHARM) analysis is a method for describing 3D shapes using a series of mathematical functions defined on the surface of a sphere. It works like a 3D version of Fourier analysis, breaking down complex shapes into components of different spatial frequencies. Each shape is first mapped onto a unit sphere and then expressed as a combination of spherical harmonic functions <span class="math inline">\(Y_l^m(\theta, \phi)\)</span>. The shape is represented by a set of coefficients <span class="math inline">\(\hat{f}(l, m)\)</span>, which capture how much each function contributes. Here, θ and ϕ are angles in spherical coordinates, l and m are order and degree respectively. Lower-order terms describe the general shape, while higher-order terms capture finer details (<a href="#fig-SPHARM-Reconstruction-by-Degree" class="quarto-xref">Figure&nbsp;3</a>).</p>
<p>This method is widely used in the field of biology, such as the analysis of skull morphology and cell morphology <span class="citation" data-cites="Link2024 Medyukhina2020 Harper2022 Hewitt2024 Grieb2022">(<a href="#ref-Link2024" role="doc-biblioref">Link et al. 2024</a>; <a href="#ref-Medyukhina2020" role="doc-biblioref">Medyukhina et al. 2020</a>; <a href="#ref-Harper2022" role="doc-biblioref">Harper, Goldstein, and Sylvester 2022</a>; <a href="#ref-Hewitt2024" role="doc-biblioref">Hewitt et al. 2024</a>; <a href="#ref-Grieb2022" role="doc-biblioref">Grieb, Barbero-García, and Lerma 2022</a>)</span>. However, there are currently very few application of SPHARM to archaeological artifacts <span class="citation" data-cites="Muller2023 Noshita2025">(<a href="#ref-Muller2023" role="doc-biblioref">Muller et al. 2023</a>; <a href="#ref-Noshita2025" role="doc-biblioref">Noshita et al. 2025</a>)</span>. Our work aims to demonstrate the usefulness of SPHARM for shape analysis of objects that are roughly spherical in shape, such as the spheroids and cores studied in this research.</p>
<p>We first imported, cleaned, and simplified the STL files of spheroids and cores to extract 3D mesh vertices, which were then converted from Cartesian (x, y, z) to spherical coordinates (r, θ, φ) <span class="citation" data-cites="Link2024 Medyukhina2020">(<a href="#ref-Link2024" role="doc-biblioref">Link et al. 2024</a>; <a href="#ref-Medyukhina2020" role="doc-biblioref">Medyukhina et al. 2020</a>)</span>. Next, we interpolated radial values onto a regular spherical grid and then decomposed them using spherical harmonics based on the Driscoll–Healy sampling scheme <span class="citation" data-cites="Link2024 Medyukhina2020">(<a href="#ref-Link2024" role="doc-biblioref">Link et al. 2024</a>; <a href="#ref-Medyukhina2020" role="doc-biblioref">Medyukhina et al. 2020</a>)</span>. The resulting coefficients were normalized for scale-invariant comparison across models.</p>
<p>From the normalized spherical harmonic coefficients, we computed the rotation-invariant power spectrum by summing the squared magnitudes of the coefficients at each degree. Each 3D shape is thus represented by its unique power spectrum, which serves as a multidimensional descriptor. To explore variation between models, we applied UMAP for dimensionality reduction and visualization <span class="citation" data-cites="Van2023">(<a href="#ref-Van2023" role="doc-biblioref">Bavel, Thiels, and Jelier 2023</a>)</span>.All these were conducted in python.</p>
<p>This study represents the first attempt in archaeology to apply SPHARM for the classification of spheroids and cores. Specifically, we included a set of standard geometric models—such as sphere, rounded cube, ellipsoid (1.2:1:0.8) and box (1.2:1:1), and disc-like (flattened, and like discoid core)—in the SPHARM analysis and UMAP. Spheroids and cores were positioned in this position based on their morphological similarity to these reference models: individuals that cluster more closely to a specific standard form exhibit corresponding shape characteristics.</p>
</section>
<section id="spherical-harmonic-energy" class="level3">
<h3 class="anchored" data-anchor-id="spherical-harmonic-energy">Spherical Harmonic Energy</h3>
<p>Additionally, we computed the spherical harmonic energy (SHE), defined as the sum of squared normalized spherical harmonic coefficients for each degree. This provides a rotation-invariant measure of shape complexity across spatial frequencies. For normalized shapes, this total energy approaches 1 for a perfect sphere, while more irregular forms yield higher values.</p>
<p>Notably, classic sphericity metrics <span class="citation" data-cites="Wadell1935">(<a href="#ref-Wadell1935" role="doc-biblioref">Wadell 1935</a>)</span> exhibit critical limitations in differentiating morphotypes with equivalent surface-area-to-volume ratios. SHE overcomes this constraint through spherical harmonic decomposition of surface morphology, and this allows it to distinguish localized irregularities (like core edge or concave) from global shape deviations (e.g., elongation) – differences that classic sphericity metrics often fail to capture.</p>
<p>We computed the total energy at degree 20, a resolution high enough to capture surface details. Lower energy values indicate more regular or rounded surfaces, while higher values reflect more irregular or angular geometries.</p>
</section>
<section id="centroid-offset" class="level3">
<h3 class="anchored" data-anchor-id="centroid-offset">Centroid offset</h3>
<p>We also used the distance between its centre of mass (CoM) and the centre of its bounding box (CoBB) as a measure of volumetric symmetry <span class="citation" data-cites="Muller2023">(<a href="#ref-Muller2023" role="doc-biblioref">Muller et al. 2023</a>)</span>, which was computed in python. A perfect sphere will have its CoM and CoBB perfectly aligned, resulting in a zero offset. As the object becomes more irregular or asymmetric, this offset increases. For each 3D model, the CoBB is defined as the midpoint of the maximum orthogonal dimensions—length (y), width (x), and thickness (z)—of its minimum bounding box. The CoM, which approximates the true mass center for objects made of homogeneous materials, is computed by weighting each triangular face of the mesh by its surface area and normalizing the result. The distance between CoM and CoBB, normalized by the artifact’s volume, serves as a quantitative indicator of sphericity: lower values indicate more spherical forms.</p>
</section>
</section>
<section id="technological-analysis" class="level2">
<h2 class="anchored" data-anchor-id="technological-analysis">Technological Analysis</h2>
<p>To investigate the production strategies of spheroids in QSY, this part aims to determine whether these artifacts were intentionally shaped and whether their manufacture followed standardized procedures. Addressing this question is crucial for evaluating whether spheroids represent a distinct technological category, separate from exhausted cores.</p>
<section id="diacritical-analysis" class="level3">
<h3 class="anchored" data-anchor-id="diacritical-analysis">Diacritical analysis</h3>
<p>We applied diacritical analysis to reconstruct the reduction sequence based on superimposition relationships among scars on spheroids <span class="citation" data-cites="tittonSubspheroidsLithicAssemblage2020 Cabanes2024">(<a href="#ref-tittonSubspheroidsLithicAssemblage2020" role="doc-biblioref">Titton et al. 2020</a>; <a href="#ref-Cabanes2024" role="doc-biblioref">Cabanès et al. 2024</a>)</span>. This method enables the identification of scars order, allowing us to figure out the organization of removals. All spheroids, polyhedrons and multifacial cores are included in the analysis to assess whether removals organization differs systematically within these groups.</p>
<p>Following the reconstruction of reduction sequences, we adopted an inductive approach to infer exploitation models of spheroids—that is, the removal patterns and associated stages employed in a spheroid. Ideally, the goal is to reconstruct the complete chaîne opératoire of spheroids—from the selection of raw material and initial blank to the final product. If consistent patterns are observed, they may indicate shared reduction schemes or conceptual templates. Furthermore, we explore whether multifacial cores and polyhedrons may represent earlier stages in spheroid reduction sequences, contributing to understanding the technological relationship between these types.</p>
</section>
<section id="orientation-analysis" class="level3">
<h3 class="anchored" data-anchor-id="orientation-analysis">Orientation analysis</h3>
<p>To further investigate technological strategies, we incorporated orientation statistics as a complementary approach. This method derives from fabric analysis originally used in sedimentology and has since been adapted to study the arrangement of flake scars on lithic artifacts. We followed the protocol developed by <span class="citation" data-cites="lin2024">Lin (<a href="#ref-lin2024" role="doc-biblioref">2024</a>)</span>, extracting scar vectors from each core and calculating eigenvalues to derive the isotropic ratio and elongation ratio, these steps were finished in Geomagic Wrap, Rhino8 and R.</p>
<p>Results are visualized using ternary plots to compare orientation statistics between spheroids and other core types. Based on our hypothesis, if spheroids were shaped following a consistent reduction sequence, they should exhibit similar and patterned orientation results. In contrast, if they merely represented exhausted cores, the orientation patterns would appear random and highly variable, similar to those of undirected polyhedron and multifacial cores.</p>
</section>
</section>
<section id="efficiency-of-shaping-strategy" class="level2">
<h2 class="anchored" data-anchor-id="efficiency-of-shaping-strategy">Efficiency of shaping strategy</h2>
<p>This section aims to investigate how the morphology of spheroids evolves during the reduction process. We hypothesize that, as reduction intensity increases, spheroids will progressively approximate a perfect sphere. This would indicate a high-efficiency shaping strategy, where each step is directed toward achieving a predefined morphological goal. To test this hypothesis, we established a set of quantitative indicators for reduction intensity and spheroid morphology.</p>
<section id="degree-of-reduction" class="level3">
<h3 class="anchored" data-anchor-id="degree-of-reduction">Degree of reduction</h3>
<p>To compute the degree of reduction we collected data on three metrics: scar number, removal ratio and scar density index (SDI). We measured scar number as total number of flake scars visible on the spheroid surface. Removal ratio was calculated as 1 minus cortex ratio, where the cortex ratio represents the proportion of cortical surface area to total surface area <span class="citation" data-cites="Cabanes2024">(<a href="#ref-Cabanes2024" role="doc-biblioref">Cabanès et al. 2024</a>)</span>. We used the removal ratio instead of the traditional cortex ratio in order to maintain a positive correlation with other reduction intensity indicators. SDI is defined as the number of flake scars divided by the total 3D surface area, the SDI serves as a robust indicator of core reduction intensity, following <span class="citation" data-cites="clarksonMeasuringCoreReduction2013">Clarkson (<a href="#ref-clarksonMeasuringCoreReduction2013" role="doc-biblioref">2013</a>)</span>. It has been demonstrated to effectively capture the dynamic nature of the reduction process. In all three metrics, higher values represent more advanced stages of reduction. Scar counts and surface area measurements were extracted using Geomagic Wrap.</p>
</section>
<section id="spheroid-shape" class="level3">
<h3 class="anchored" data-anchor-id="spheroid-shape">Spheroid shape</h3>
<p>We measured spheroid shape with four metrics: sphericity, and spherical harmonic energy (SHE), along with mean edge angle, mean surface curvature.</p>
<p>Higher mean edge angles suggest a more spherical geometry. Ten edge intersections were randomly sampled per spheroid. Angles were calculated following <span class="citation" data-cites="tittonSubspheroidsLithicAssemblage2020">Titton et al. (<a href="#ref-tittonSubspheroidsLithicAssemblage2020" role="doc-biblioref">2020</a>)</span> by constructing triangles at ridge intersections, extracting vertex coordinates in Geomagic Wrap, and computed angles from the coordinates using trigonometric functions in R.</p>
<p>Mean surface curvature is a proxy for surface roughness, and higher mean surface curvature indicates a smoother surface. We estimated local curvature using the k-nearest neighbors method to fit a best-fit plane at each vertex <span class="citation" data-cites="Muller2023">(<a href="#ref-Muller2023" role="doc-biblioref">Muller et al. 2023</a>)</span>. The deviation between actual surface points and this fitted plane reflects surface roughness. The calculation steps were completed in Python.</p>
<p>Together, these four variables allowed us to assess whether more extensively reduced spheroids display more standardized, symmetrical, and regular morphologies—characteristics expected in deliberate shaping strategies. We conducted Spearman’s rank correlation analysis between two sets of variables—reduction intensity indicators and morphological attributes. This non-parametric method is appropriate for small sample sizes and data that do not follow a normal distribution. Spheroids and sub-spheroids from the QSY site were included in the analysis.</p>
</section>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="results-of-morphometric-analysis" class="level2">
<h2 class="anchored" data-anchor-id="results-of-morphometric-analysis">Results of Morphometric analysis</h2>
<div class="cell">
<div id="tbl-1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary of core typology and morphological parameters.
</figcaption>
<div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">ID</th>
<th style="text-align: left;">Blank type</th>
<th style="text-align: left;">Blank morphology</th>
<th style="text-align: left;">Final morphology</th>
<th style="text-align: left;">Typology</th>
<th style="text-align: left;">typology by SPHARM</th>
<th style="text-align: right;">Sphericity</th>
<th style="text-align: right;">SPHARM power</th>
<th style="text-align: right;">Centroid offset</th>
<th style="text-align: left;">Cortex covered</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">QSY_A_0256</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Ellipsoid</td>
<td style="text-align: right;">0.8658388</td>
<td style="text-align: right;">1.020296</td>
<td style="text-align: right;">1.571368</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_0562</td>
<td style="text-align: left;">Nodule</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Discoid-like</td>
<td style="text-align: right;">0.8269944</td>
<td style="text-align: right;">1.042784</td>
<td style="text-align: right;">1.490442</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_0570</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Discoid-like</td>
<td style="text-align: right;">0.8255318</td>
<td style="text-align: right;">1.079571</td>
<td style="text-align: right;">1.282095</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_0576</td>
<td style="text-align: left;">Flake</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Multifacial</td>
<td style="text-align: left;">Discoid-like</td>
<td style="text-align: right;">0.8091313</td>
<td style="text-align: right;">1.049576</td>
<td style="text-align: right;">2.104250</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_0579</td>
<td style="text-align: left;">Nodule</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.7988300</td>
<td style="text-align: right;">1.054399</td>
<td style="text-align: right;">1.161040</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_0680</td>
<td style="text-align: left;">Nodule</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8032364</td>
<td style="text-align: right;">1.039023</td>
<td style="text-align: right;">1.285673</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_0682</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.9166715</td>
<td style="text-align: right;">1.010390</td>
<td style="text-align: right;">6.530839</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_0699</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8807450</td>
<td style="text-align: right;">1.024810</td>
<td style="text-align: right;">2.363453</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_0700</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.8933988</td>
<td style="text-align: right;">1.017122</td>
<td style="text-align: right;">1.039335</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_0702</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Multifacial</td>
<td style="text-align: left;">Ellipsoid</td>
<td style="text-align: right;">0.8419195</td>
<td style="text-align: right;">1.042415</td>
<td style="text-align: right;">6.912960</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_0735</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.8678116</td>
<td style="text-align: right;">1.019932</td>
<td style="text-align: right;">2.539858</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_0938</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8690457</td>
<td style="text-align: right;">1.027144</td>
<td style="text-align: right;">4.001371</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_1098</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Rounded</td>
<td style="text-align: left;">Spheroid</td>
<td style="text-align: left;">Ellipsoid</td>
<td style="text-align: right;">0.9191438</td>
<td style="text-align: right;">1.012857</td>
<td style="text-align: right;">1.016149</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_1111</td>
<td style="text-align: left;">Nodule</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Ellipsoid</td>
<td style="text-align: right;">0.8717981</td>
<td style="text-align: right;">1.022741</td>
<td style="text-align: right;">1.109560</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_1246</td>
<td style="text-align: left;">Nodule</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Subspheroid</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.8934587</td>
<td style="text-align: right;">1.010859</td>
<td style="text-align: right;">1.957580</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_1304</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Multifacial</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.9274082</td>
<td style="text-align: right;">1.012530</td>
<td style="text-align: right;">3.038120</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_1307</td>
<td style="text-align: left;">Nodule</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Discoid-like</td>
<td style="text-align: right;">0.8675301</td>
<td style="text-align: right;">1.036793</td>
<td style="text-align: right;">3.550725</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_1333</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8606773</td>
<td style="text-align: right;">1.031251</td>
<td style="text-align: right;">2.519639</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_1517</td>
<td style="text-align: left;">Flake</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Multifacial</td>
<td style="text-align: left;">Discoid-like</td>
<td style="text-align: right;">0.7955195</td>
<td style="text-align: right;">1.075345</td>
<td style="text-align: right;">3.171066</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_1584</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.8547083</td>
<td style="text-align: right;">1.018949</td>
<td style="text-align: right;">7.942392</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_1777</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Rounded</td>
<td style="text-align: left;">Spheroid</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.8967779</td>
<td style="text-align: right;">1.011231</td>
<td style="text-align: right;">1.435167</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_1941</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Subspheroid</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.9011202</td>
<td style="text-align: right;">1.011462</td>
<td style="text-align: right;">3.964506</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_2048</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Subspheroid</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8911406</td>
<td style="text-align: right;">1.030040</td>
<td style="text-align: right;">6.442905</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_2049</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Multifacial</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8688198</td>
<td style="text-align: right;">1.031176</td>
<td style="text-align: right;">1.426403</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_2213</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Subspheroid</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.8779463</td>
<td style="text-align: right;">1.010787</td>
<td style="text-align: right;">3.005867</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_2381</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Multifacial</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8757082</td>
<td style="text-align: right;">1.027697</td>
<td style="text-align: right;">4.231788</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_2599</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Ellipsoid</td>
<td style="text-align: right;">0.9021322</td>
<td style="text-align: right;">1.016534</td>
<td style="text-align: right;">4.845816</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_2600</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Rounded</td>
<td style="text-align: left;">Spheroid</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.9272417</td>
<td style="text-align: right;">1.010491</td>
<td style="text-align: right;">1.862968</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_2611</td>
<td style="text-align: left;">Nodule</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Multifacial</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8203610</td>
<td style="text-align: right;">1.040002</td>
<td style="text-align: right;">1.144922</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_2717</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Subspheroid</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.9045169</td>
<td style="text-align: right;">1.011386</td>
<td style="text-align: right;">3.637126</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_2723</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Rounded</td>
<td style="text-align: left;">Spheroid</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.9067064</td>
<td style="text-align: right;">1.009120</td>
<td style="text-align: right;">5.505126</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_2797</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Rounded</td>
<td style="text-align: left;">Spheroid</td>
<td style="text-align: left;">Sphere</td>
<td style="text-align: right;">0.9376838</td>
<td style="text-align: right;">1.004382</td>
<td style="text-align: right;">2.950471</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_B_003</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Rounded</td>
<td style="text-align: left;">Spheroid</td>
<td style="text-align: left;">Rounded cube</td>
<td style="text-align: right;">0.9151881</td>
<td style="text-align: right;">1.014738</td>
<td style="text-align: right;">3.890027</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_B_072</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Subspheroid</td>
<td style="text-align: left;">Ellipsoid</td>
<td style="text-align: right;">0.9021261</td>
<td style="text-align: right;">1.020418</td>
<td style="text-align: right;">2.564553</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_B_136</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Ellipsoid</td>
<td style="text-align: right;">0.8791311</td>
<td style="text-align: right;">1.018891</td>
<td style="text-align: right;">1.867975</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_B_140</td>
<td style="text-align: left;">Nodule</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8858050</td>
<td style="text-align: right;">1.024280</td>
<td style="text-align: right;">4.030924</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_B_159</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Pyramidal</td>
<td style="text-align: left;">Multifacial</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8631108</td>
<td style="text-align: right;">1.024487</td>
<td style="text-align: right;">4.939933</td>
<td style="text-align: left;">Y</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_B_168</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8992439</td>
<td style="text-align: right;">1.023644</td>
<td style="text-align: right;">3.083931</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_B_186</td>
<td style="text-align: left;">Nodule</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Polyhedral</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Box</td>
<td style="text-align: right;">0.8688678</td>
<td style="text-align: right;">1.026525</td>
<td style="text-align: right;">2.674256</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_B_189</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Subspheroid</td>
<td style="text-align: left;">Ellipsoid</td>
<td style="text-align: right;">0.9045078</td>
<td style="text-align: right;">1.016141</td>
<td style="text-align: right;">2.324629</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_B_320</td>
<td style="text-align: left;">Cobble</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Discoid-like</td>
<td style="text-align: right;">0.8589857</td>
<td style="text-align: right;">1.052747</td>
<td style="text-align: right;">1.606183</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_B_435</td>
<td style="text-align: left;">Nodule</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Cubical</td>
<td style="text-align: left;">Polyhedron</td>
<td style="text-align: left;">Ellipsoid</td>
<td style="text-align: right;">0.8578307</td>
<td style="text-align: right;">1.020420</td>
<td style="text-align: right;">2.279425</td>
<td style="text-align: left;">Y</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-SPHARM-Reconstruction-by-Degree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-SPHARM-Reconstruction-by-Degree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/SPHARM_reconstruction.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-SPHARM-Reconstruction-by-Degree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Shape reconstruction of archaeological spheroids using SPHARM (various lmax levels)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-UMAP-SPHARM-clusters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-UMAP-SPHARM-clusters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/UMAP_SPHARM_clusters.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-UMAP-SPHARM-clusters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: UMAP plot showing distinct clusters of shapes derived from SPHARM
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-UMAP-SPHARM-samples" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-UMAP-SPHARM-samples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/UMAP_SPHARM_samples.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-UMAP-SPHARM-samples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: UMAP plot of SPHARM-derived shape features colored by types
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-Correlation-SPHARMpower-Sphericity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Correlation-SPHARMpower-Sphericity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/Correlation_SPHARMpower_Sphericity.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Correlation-SPHARMpower-Sphericity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Correlation analysis between SPHARMpower and Sphericity
</figcaption>
</figure>
</div>
</div>
</div>
<p>We applied spherical sphericity index, harmonics analysis, and centroid offset measurements to both the spheroids (n = 42) and all other multifacial and polyhedron cores (n = 29) in the assemblage of QSY. These analyses aim to assess whether spheroids are morphologically distinct from other cores, and whether they exhibit standardized shapes—an essential criterion for evaluating the existence of deliberate shaping strategies and a goal product. In addition, we compare quantitative outcomes with traditional typological classifications to assess their consistency. We present a summary table listing each core’s blank morphology and type, final morphology, and cortex coverage here in <a href="#tbl-1" class="quarto-xref">Table&nbsp;1</a>.</p>
<p>Sphericity analysis reveals a clear difference between spheroids and multifacial cores/polyhedra. The mean sphericity of spheroids (0.906) is notably higher than that of multifacial cores and polyhedron (0.861), with a Mann-Whitney U test yielding U = 37, p = <span class="math inline">\(3.99 \times 10^{-5}\)</span>. This result indicates that spheroids possess a more spherical geometry overall, supporting their typological classification.</p>
<p>We conducted shape analysis based on spherical harmonic decomposition, setting the maximum degree to 20 (lmax=20,<a href="#fig-SPHARM-Reconstruction-by-Degree" class="quarto-xref">Figure&nbsp;3</a>). This choice ensures that sufficient geometric detail is captured while avoiding high-frequency noise and overfitting artifacts such as the Gibbs phenomenon. After normalization, all models have their degree 0 (l=0) coefficient set to 1, allowing for meaningful comparison across different models.</p>
<p>A Variance Analysis was performed on the power of each harmonic degree. The results indicate that l= 2 and l=3 exhibit the highest variance across the sample, suggesting that these low-order terms capture the most significant shape variation. Specifically, l=2 reflects global asymmetries—such as elongation or flattening—while degree 3 is more sensitive to localized features like curvature and edge protrusions.</p>
<p>To visualize the structure of shape variation, we applied UMAP to the normalized power spectrum. The UMAP projection reveals distinct clusters in the first two dimensions of the shape space. These clusters correspond to reference models, sphere, rounded cube, ellipsoid, box and disc-shaped core (<a href="#fig-UMAP-SPHARM-clusters" class="quarto-xref">Figure&nbsp;4</a>). This demonstrates that these cores occupy distinguishable regions in the harmonic shape space, with proximity to the sphere or elongation/flattening along specific axes emerging as key differentiating features. Most artifacts typologically classified as spheroids or sub-spheroids were grouped into the “sphere” , “cube” and “ellipsoid” clusters, indicating their consistent, near-spherical shapes (<a href="#fig-UMAP-SPHARM-samples" class="quarto-xref">Figure&nbsp;5</a>). However, some Multifacial cores and Polyhedron also appeared in the near-spherical region. This can be attributed to their high cortex coverage or limited flake removals, which likely preserved their originally rounded forms and led to their grouping alongside more intentionally shaped spheroids.</p>
<p>We then tested whether the UMAP-based groupings also correspond to differences in sphericity using a Kruskal–Wallis test, which yielded <span class="math inline">\(\chi^2\)</span> = 18.65, df = 3, p = <span class="math inline">\(3.23 \times 10^{-4}\)</span>. The result shows statistically significant differences in sphericity among the shape clusters, further supporting the effectiveness of the spherical harmonic approach in capturing meaningful morphological variation (<a href="#fig-Correlation-SPHARMpower-Sphericity" class="quarto-xref">Figure&nbsp;6</a>).</p>
<p>The spherical harmonic energy (SHE), a novel metric introduced herein, quantifies the geometric approximation of core morphology to an ideal sphere. Normalized SHE approaching unity indicates progressively spherical configurations, while deviations from unity reflect morphological irregularity. Our analysis demonstrates significant negative correlation between SHE and classic sphericity measures (r = -0.83, df = 40, p = <span class="math inline">\(6.88 \times 10^{-12}\)</span>)), validating its efficacy as a proxy of sphericity.</p>
<p>Statistical comparisons reveal distinct SHE distributions between morphological classes: spheroids and sub-spheroids exhibit mean SHE = 1.013 (SD = 0.006), whereas multifacial cores and polyhedron demonstrate significantly higher irregularity (mean SHE = 1.032, SD = 0.017). The Kruskal-Wallis test confirms robust inter-group divergence (<span class="math inline">\(\chi^2\)</span> = 19.11, df = 3, p = <span class="math inline">\(2.60 \times 10^{-4}\)</span>), proving the distinguishability of spheroids in QSY.</p>
<p>The pursuit of a standardized spherical form among spheroids is further supported by our findings. Using the Coefficient of Variation (CV)—defined as the sample standard deviation divided by the sample mean—we assessed the consistency of sphericity within the spheroids. <span class="citation" data-cites="Eerkens2001">Eerkens and Bettinger (<a href="#ref-Eerkens2001" role="doc-biblioref">2001</a>)</span> suggested that a CV of under 1.7% (0.017) is a realistic threshold for manually-produced archaeological artifacts. Both sphericity and SHE values yielded low CVs (0.017 and 0.006, respectively), indicating that sub/spheroids maintain a highly standardized rounded shape. In contrast, multifacial cores combined with polyhedron has a higher CV of 0.039 and 0.017 respectively.</p>
</section>
<section id="results-of-technological-analysis" class="level2">
<h2 class="anchored" data-anchor-id="results-of-technological-analysis">Results of technological analysis</h2>
<p>The diacritical analysis of spheroid surfaces reveals a structured and recurrent reduction sequence comprising the following phases (<a href="#fig-spheroids-2797-1098" class="quarto-xref">Figure&nbsp;8</a>). Phase 1 was a unidirectional or bidirectional total exploitation, belonging to one kind of volume exploitation. Large and flat surfaces of the cobble were selected as platforms for striking toward the opposite surface. Knapping proceeded until the peripheral volume was fully exploited, resulting in an approximately cubic form. Phase 2 was peripheral centripetal exploitation. In this phase, previous removals in phase 1 serve as platforms for centripetal flaking around the core periphery. This represents a surface exploitation strategy. A notable feature is the angle between the face’s ventral surface and platform (i.e.&nbsp;core edge angle), which often exceeds 90°, forming a secant plan [citation] rather than parallel plan. This phase contributes significantly to the increasingly spherical shape of the artefact. Phase 3 was the production of small scars on ridges or intersections of previous flake scars, resulting in a rounding and smoother surface, further enhancing sphericality. It is important to note that due to the high degree of reduction intensity observed in most spheroids, phases prior to the visible sequence were often obliterated. We hypothesize the existence of a Phase 0, potentially involving roughing-out of the cobble or an earlier cycle of Phases 1–3.</p>
<!-- insert QSYA-1098-4.png and QSYA-2797-0.png about here, with the texure paired with the phase annotations figures, like a 2x2 panel, add a legend to indicate the meaning of the colours -->
<p>Scar orientation analysis further supports the interpretation of a systematic reduction sequence in the production of QSY spheroids. <a href="#fig-benn-ternary-plot" class="quarto-xref">Figure&nbsp;7</a> shows that spheroids tend to cluster together, with elongation ratios ranging from 0.403 to 0.637 and isotropy ratios from 0.164 to 0.497. These elongation ratios suggest that the spheroids underwent unidirectional or bidirectional total exploitation, typical of Phase 1, resulting in relatively high elongation values. In addition, the peripheral centripetal exploitation, namely Phase 2, appears to have contributed to a certain degree of isotropy in scar arrangement—higher isotropy ratios are associated with more spherical shapes. Subspheroids exhibit greater variability in both elongation and isotropy ratios, indicating less consistent reduction intensity.</p>
<p>Multifacial cores and polyhedrons display a wide and dispersed distribution in the ternary plot, without forming any distinctive cluster. Their scar patterns show considerable variability in both elongation and isotropy, reinforcing the interpretation that these cores lack removal organization and reflect a SSDA. Multifacial cores typically exploit natural angles with core rotation occurring without a predetermined plan, which belongs to an opportunistic flaking strategy, while polyhedrons—despite showing a higher degree of reduction—follow a similarly unstructured sequence. This distinction highlights the fundamental technological difference between polyhedrons and spheroids at QSY, where they used to be considered as a continuous reduction process: polyhedrons represent exhausted cores, whereas spheroids reflect the presence of a conceptual template and systematic reduction plan.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-benn-ternary-plot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-benn-ternary-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="paper_files/figure-html/fig-benn-ternary-plot-1.png" class="img-fluid figure-img" width="4200">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-benn-ternary-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Ternary plot showing flake scar orientation analysis
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-spheroids-2797-1098" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-spheroids-2797-1098-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/spheroids_2797_1098.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-spheroids-2797-1098-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Diacritical analysis of QSY spheroids
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-shaping-process" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-shaping-process-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/shaping_process.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-shaping-process-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: hypothesis of QSY spheroid shaping process
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="efficiency-of-shaping-strategy-1" class="level2">
<h2 class="anchored" data-anchor-id="efficiency-of-shaping-strategy-1">Efficiency of shaping strategy</h2>
<div class="cell">
<div id="tbl-2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Summary of spheroid shaping intensity and shape features.
</figcaption>
<div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 17%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">ID</th>
<th style="text-align: right;">Scar number</th>
<th style="text-align: right;">Removal ratio</th>
<th style="text-align: right;">SDI</th>
<th style="text-align: right;">Edge angle mean</th>
<th style="text-align: right;">Curvature</th>
<th style="text-align: right;">Sphericity</th>
<th style="text-align: right;">SPHARM power</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">QSY_A_1098</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">0.973</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">128.338</td>
<td style="text-align: right;">7.998</td>
<td style="text-align: right;">0.919</td>
<td style="text-align: right;">1.013</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_1246</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0.921</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">123.936</td>
<td style="text-align: right;">8.090</td>
<td style="text-align: right;">0.893</td>
<td style="text-align: right;">1.011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_1777</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.927</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">122.208</td>
<td style="text-align: right;">7.979</td>
<td style="text-align: right;">0.897</td>
<td style="text-align: right;">1.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_1941</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.681</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">109.423</td>
<td style="text-align: right;">9.902</td>
<td style="text-align: right;">0.901</td>
<td style="text-align: right;">1.011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_2048</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0.851</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">118.574</td>
<td style="text-align: right;">8.133</td>
<td style="text-align: right;">0.891</td>
<td style="text-align: right;">1.030</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_2213</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0.922</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">114.985</td>
<td style="text-align: right;">8.873</td>
<td style="text-align: right;">0.878</td>
<td style="text-align: right;">1.011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_2600</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0.852</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">124.385</td>
<td style="text-align: right;">7.145</td>
<td style="text-align: right;">0.927</td>
<td style="text-align: right;">1.010</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_2717</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0.860</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">122.426</td>
<td style="text-align: right;">8.954</td>
<td style="text-align: right;">0.905</td>
<td style="text-align: right;">1.011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_A_2723</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">0.918</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">134.926</td>
<td style="text-align: right;">8.275</td>
<td style="text-align: right;">0.907</td>
<td style="text-align: right;">1.009</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_A_2797</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">0.960</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">135.403</td>
<td style="text-align: right;">7.453</td>
<td style="text-align: right;">0.938</td>
<td style="text-align: right;">1.004</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_B_003</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.647</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">120.931</td>
<td style="text-align: right;">6.750</td>
<td style="text-align: right;">0.915</td>
<td style="text-align: right;">1.015</td>
</tr>
<tr class="even">
<td style="text-align: left;">QSY_B_072</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.623</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">115.484</td>
<td style="text-align: right;">8.008</td>
<td style="text-align: right;">0.902</td>
<td style="text-align: right;">1.020</td>
</tr>
<tr class="odd">
<td style="text-align: left;">QSY_B_189</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.782</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">117.941</td>
<td style="text-align: right;">7.626</td>
<td style="text-align: right;">0.905</td>
<td style="text-align: right;">1.016</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-spearman-correlation-matrix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-spearman-correlation-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="paper_files/figure-html/fig-spearman-correlation-matrix-1.png" class="img-fluid figure-img" width="4200">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-spearman-correlation-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Spearman correlation matrix of shape variables. Red star indicates p &lt; 0.05
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-spearman-correlation-matrix" class="quarto-xref">Figure&nbsp;10</a> shows significant positive correlations among the three variables representing reduction intensity: scar number, removal ratio, and SDI. Among them, scar counts show significant positive correlations with both removal ratio (ρ = 0.74, p = <span class="math inline">\(3.56 \times 10^{-3}\)</span>) and SDI (ρ = 0.64, p = <span class="math inline">\(1.87 \times 10^{-2}\)</span>). Removal ratio and SDI exhibit a stronger and more highly significant correlation (ρ = 0.89, p = <span class="math inline">\(4.57 \times 10^{-5}\)</span>). These two variables incorporate surface area in their calculation, making them more effective in capturing the density and intensity of reduction, and therefore more reliable indicators of the shaping process in spheroids.</p>
<p>Among the shape descriptors of spheroids, several significant correlations were observed. Mean edge angle was positively correlated with sphericity (ρ = 0.68, p = <span class="math inline">\(1.12 \times 10^{-2}\)</span>) and negatively correlated with SPHARM power (ρ = -0.59, p = <span class="math inline">\(3.46 \times 10^{-2}\)</span>), indicating that greater edge angles are associated with more spherical and regular forms. As noted in previous studies, mean edge angle is a key variable in capturing the morphology of spheroids [citation]. This correlation between edge angle and sphericity may help explain why spheroids were often interpreted as exhausted cores in earlier research [citation]. Indeed, spheroids must be significantly reduced, as achieving a near-perfect spherical shape typically results in increased edge angles, making further flake removal difficult. However, the reverse is not necessarily true—not all exhausted cores evolve into spheroids.</p>
<p>Curvature was only significantly correlated with sphericity (ρ = -0.59, p = <span class="math inline">\(3.46 \times 10^{-2}\)</span>), suggesting that smoother surfaces tend to approximate spheres more closely. Its lack of correlation with other variables may reflect its focus on local surface texture, while edge angle and SPHARM power capture broader aspects of shape regularity and symmetry. The weak correlation between sphericity and SPHARM power may result from the small sample size or their different sensitivities: sphericity, based on area and volume, tolerates surface variation, while SPHARM power responds more to asymmetry and surface irregularity. Thus, even in similarly spherical specimens, surface differences can produce substantial variation in SPHARM power. The analysis of spheroid shape variables indicates that mean edge angle, curvature, sphericity, and SPHARM power each capture distinct aspects of spheroid morphology, which explains the varying strengths of correlation observed among them.</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="do-qianshangying-spheroids-represent-of-a-shaping-strategy" class="level2">
<h2 class="anchored" data-anchor-id="do-qianshangying-spheroids-represent-of-a-shaping-strategy">Do Qianshangying Spheroids represent of a Shaping Strategy?</h2>
<p>According to the results of morphological and technological analysis, we can summarize the technical strategy employed in the production of faceted spheroids in QSY. This strategy consists of a series of sequential phases (<a href="#fig-shaping-process" class="quarto-xref">Figure&nbsp;9</a>): a potential rough-out phase, volume exploitation aimed at forming a cubic shape, surface exploitation to approximate a spheroidal geometry, edge refinement, and potentially the repetition of earlier phases. The existence of a repetitive phase is supported by the observation that while the original cobble blanks in QSY display considerable size variation, the finished spheroids, although two of them are relatively large or small, mostly cluster around a diameter of 6–9 cm (<a href="#fig-core-spheroid-size" class="quarto-xref">Figure&nbsp;2</a>). This suggests that the production of spheroids may have involved multiple cycles of reduction, and further implies that a diameter of 6–9 cm was considered an optimal or intended size in the knapping process.</p>
<p>Therefore, it can be inferred that the QSY hominin deliberately employed a standardized production approach to create spheroids with consistent and formalized shapes. The technological strategy reflected in the QSY facted spheroids includes the use of conceptual template, standardized production, and the achievement of a target product, which together demonstrate that this was a shaping strategy. This stands in contrast to flaking strategies, where the primary objective is the removal of usable flakes or débitage rather than the shaping of a cobble into a predetermined morphology <span class="citation" data-cites="inizan1999 duke2021">(<a href="#ref-inizan1999" role="doc-biblioref">Inizan, Reduron-Ballinger, and Roche 1999</a>; <a href="#ref-duke2021" role="doc-biblioref">Duke, Feibel, and Harmand 2021</a>)</span>.</p>
<p>The origins of shaping strategies are most commonly linked to the Acheulean, particularly those exemplified by bifacial shaping strategies on handaxes <span class="citation" data-cites="isaac1986foundation">(<a href="#ref-isaac1986foundation" role="doc-biblioref">Glynn L. Isaac 1986</a>)</span>. These strategies gradually became more refined, with mature bifacial shaping marked by the concept of bifacial symmetry, thinning and edge refinement, and the achievement of a standardized final shape <span class="citation" data-cites="beyene2013">(<a href="#ref-beyene2013" role="doc-biblioref">Beyene et al. 2013</a>)</span>. Compared to flaking technology in Oldowan, these processes demand greater cognitive planning and precise manual control <span class="citation" data-cites="wynn1995 stout2015">(<a href="#ref-wynn1995" role="doc-biblioref">Wynn 1995</a>; <a href="#ref-stout2015" role="doc-biblioref">Stout et al. 2015</a>)</span>. Although the spheroids from QSY do not qualify as Large Cutting Tools (LCTs), nor does the site yield other typically Acheulean products, the faceted spheroids nonetheless exhibit a level of technological and morphological complexity comparable to that of LCTs. They also share key features, including a hierarchical and standardized reduction sequence and a high degree of symmetry and surface regularity in the final product.</p>
<p>These findings also contribute to the long-standing debate over the nature of spheroids—whether they should be interpreted as byproducts of flake production (exhausted cores), or as targeted end products of shaping strategies. In the case of QSY facted spheroids, the evidence strongly supports the latter. Faceted spheroids recovered from other Early Pleistocene sites in anBarranco Leo ́nd and ’Ubeidiya have also been reported to show evidence consistent with shaping strategy <span class="citation" data-cites="Muller2023 tittonSubspheroidsLithicAssemblage2020">(<a href="#ref-Muller2023" role="doc-biblioref">Muller et al. 2023</a>; <a href="#ref-tittonSubspheroidsLithicAssemblage2020" role="doc-biblioref">Titton et al. 2020</a>)</span>. These intentionally shaped spheroids appear contemporaneous with, or even predate, the emergence of Acheulean technology. It is important to note, however, that many spheroids from East Africa may not fall into this category. As noted by <span class="citation" data-cites="mora2005">(<a href="#ref-mora2005" role="doc-biblioref">Mora and De La Torre 2005</a>)</span>, these quartz-based spheroids may have been produced through percussive techniques. They are often covered with battering marks, exhibit smoother surfaces, and lack ridges—features that suggest they may be better classified as bolas within a typological framework <span class="citation" data-cites="leakey1971">(<a href="#ref-leakey1971" role="doc-biblioref">Leakey 1971</a>)</span>.</p>
<p>Another issue we aim to address is the relationship between polyhedrons, spheroids, and bolas. While no bolas were identified at the QSY site, our quantitative analyses clearly differentiate polyhedrons from spheroids. These two artifact types differ in size, morphology, and production sequence. Polyhedrons at QSY represent heavily reduced cores, whose edge angle increase results from extensive flake removal. Their primary purpose lies in producing flake, placing them within a flaking strategy. In contrast, spheroids were intentionally shaped as end products, reflecting a shaping strategy. These two technological approaches of flaking and shaping strategies coexisted at QSY, indicating a diversity of reduction goals.</p>
<p>However, we found that although the morphology and reduction technology of spheroids and polyhedrons can be clearly distinguished, spheroids in early phases may be difficult to differentiate from cores. In their initial phases of reduction, spheroids often resemble cores due to similar flake removal patterns. At this stage, they may be classified as cores, especially since the flakes produced during the initial shaping are themselves usable. However, it remains unclear whether this typological transformation was intentional or unplanned. In addition, the spheroids at QSY appear to have undergone another form of typological transformation—from hammerstones to spheroids. one specimen initially served as percussive tools but were later subjected to flake removal, suggesting a shift in function from battering to shaping.</p>
</section>
<section id="the-technological-and-typological-variability-of-spheroids-in-china" class="level2">
<h2 class="anchored" data-anchor-id="the-technological-and-typological-variability-of-spheroids-in-china">The Technological and Typological Variability of Spheroids in China</h2>
<div class="cell">
<div id="tbl-3" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Summary of core typology and morphological parameters.
</figcaption>
<div aria-describedby="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 19%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">site</th>
<th style="text-align: left;">geographic location</th>
<th style="text-align: left;">geochronology</th>
<th style="text-align: left;">site type</th>
<th style="text-align: left;">industry type</th>
<th style="text-align: left;">number of spheroids/bolas</th>
<th style="text-align: left;">raw material</th>
<th style="text-align: left;">production technology</th>
<th style="text-align: left;">remarks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">choushuihe</td>
<td style="text-align: left;">Lantian, Shanxi</td>
<td style="text-align: left;">survey-collected</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">core and flake industry</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">quartz</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">zhoukoudian</td>
<td style="text-align: left;">beijing</td>
<td style="text-align: left;">early Middle Pleistocene</td>
<td style="text-align: left;">cave</td>
<td style="text-align: left;">core and flake industry, but LCTs included</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">quartz; quartzite; sandstone</td>
<td style="text-align: left;">battering on polyhedron</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">kehe</td>
<td style="text-align: left;">ruicheng, shanxi</td>
<td style="text-align: left;">Middle Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">tradition of large flake and large triangular points</td>
<td style="text-align: left;">＞3</td>
<td style="text-align: left;">quartzite</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">resemble QSY</td>
</tr>
<tr class="even">
<td style="text-align: left;">dingcun79:01/02</td>
<td style="text-align: left;">xiangfen, shanxi</td>
<td style="text-align: left;">Middle Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">tradition of large flake and large triangular points</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">limestone; sandstone</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dingcun76:006/007/008; 79:05; 80:01</td>
<td style="text-align: left;">xiangfen, shanxi</td>
<td style="text-align: left;">Late Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">tradition of large flake and large triangular points</td>
<td style="text-align: left;">98</td>
<td style="text-align: left;">limestone; diorite; quartzite; sandstone</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">resemble QSY</td>
</tr>
<tr class="even">
<td style="text-align: left;">dingcun77:01</td>
<td style="text-align: left;">xiangfen, shanxi</td>
<td style="text-align: left;">Late Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">LP-Microlithic</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">limestone; sandstone</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">xigou</td>
<td style="text-align: left;">quwo, shanxi</td>
<td style="text-align: left;">survey-collected</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">tradition of large flake and large triangular points</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">limestone</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">shuigou/huixinggou</td>
<td style="text-align: left;">sanmenxia, henan</td>
<td style="text-align: left;">Middle Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">tradition of large flake and large triangular points</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">lava; quartz; breccia</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">resemble QSY</td>
</tr>
<tr class="odd">
<td style="text-align: left;">xiaokongshan lower cave</td>
<td style="text-align: left;">nanzhao, henan</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">cave</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">quartzite</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">zhangjiatan/xiangou</td>
<td style="text-align: left;">lixian, hunan</td>
<td style="text-align: left;">survey-collected</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">tradition of large flake and large triangular points</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">sandstone</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Deshan Second Brick Factory</td>
<td style="text-align: left;">changde, hunan</td>
<td style="text-align: left;">survey-collected</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">tradition of large flake and large triangular points</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">sandstone; dolomite</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">resemble QSY</td>
</tr>
<tr class="even">
<td style="text-align: left;">huzhua Mount.</td>
<td style="text-align: left;">jinshi, hunan</td>
<td style="text-align: left;">survey-collected</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">tradition of large flake and large triangular points</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">sandstone</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">resemble QSY</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fangniu Mount.</td>
<td style="text-align: left;">jurong, jiangsu</td>
<td style="text-align: left;">late Middle Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">LCTs included</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">sandstone; dolomite</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">yaoshi basin</td>
<td style="text-align: left;">shangzhou, shanxi</td>
<td style="text-align: left;">late Middle Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">LCTs included</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">quartz</td>
<td style="text-align: left;">pecking after flaking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">shangdan basin</td>
<td style="text-align: left;">southern shanxi</td>
<td style="text-align: left;">late Middle Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">Achulean</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">quartz sandstone</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">xujiayao1974</td>
<td style="text-align: left;">yanggao, shanxi</td>
<td style="text-align: left;">late Middle Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">core and flake industry to MP</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">quartz; lava; quartzite; limestone</td>
<td style="text-align: left;">pecking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">xujiayao1976</td>
<td style="text-align: left;">yanggao, shanxi</td>
<td style="text-align: left;">late Middle Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">core and flake industry to MP</td>
<td style="text-align: left;">1059</td>
<td style="text-align: left;">?</td>
<td style="text-align: left;">?</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">xujiayao1977</td>
<td style="text-align: left;">yanggao, shanxi</td>
<td style="text-align: left;">late Middle Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">core and flake industry to MP</td>
<td style="text-align: left;">32</td>
<td style="text-align: left;">quartz; dolomite</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">xujiayao2017-</td>
<td style="text-align: left;">yanggao, shanxi</td>
<td style="text-align: left;">late Middle Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">core and flake industry to MP</td>
<td style="text-align: left;">23</td>
<td style="text-align: left;">lava; quartz sandstone; granite</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">longgangsi</td>
<td style="text-align: left;">hanzhong, shanxi</td>
<td style="text-align: left;">survey-collected</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">Achulean</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">quartz; quartzite; lava</td>
<td style="text-align: left;">pecking after flaking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hejialiang</td>
<td style="text-align: left;">hanzhong, shanxi</td>
<td style="text-align: left;">70-80ka</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">LCTs included</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">quartz; lava</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">fanba</td>
<td style="text-align: left;">hanzhong, shanxi</td>
<td style="text-align: left;">180-25ka</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">core and flake industry</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">quartz</td>
<td style="text-align: left;">pecking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dangcheng</td>
<td style="text-align: left;">heshun, shanxi</td>
<td style="text-align: left;">Late Pleistocene</td>
<td style="text-align: left;">cave</td>
<td style="text-align: left;">core and flake industry</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">quartz</td>
<td style="text-align: left;">flaking or pecking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">hezhigou</td>
<td style="text-align: left;">jingchuan, gansu</td>
<td style="text-align: left;">Late Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">quartzite</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">liujiacha</td>
<td style="text-align: left;">huanxian, gansu</td>
<td style="text-align: left;">Late Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">quartzite; dolomite</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">liaohe river</td>
<td style="text-align: left;">anyi, anhui</td>
<td style="text-align: left;">Late Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">LCTs included</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">quartz</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mujiaqiao</td>
<td style="text-align: left;">lijiang, yunnan</td>
<td style="text-align: left;">Late Pleistocene</td>
<td style="text-align: left;">open-air</td>
<td style="text-align: left;">core and flake industry</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">limestone; quartz</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">resemble QSY</td>
</tr>
<tr class="even">
<td style="text-align: left;">jinsitai</td>
<td style="text-align: left;">Dongwuzhumuqin Banner, Inner Mongolia</td>
<td style="text-align: left;">Late Pleistocene</td>
<td style="text-align: left;">cave</td>
<td style="text-align: left;">MP-Mousterian</td>
<td style="text-align: left;">169</td>
<td style="text-align: left;">lava; limestone; quartz</td>
<td style="text-align: left;">flaking</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>site data: 1. Mujiaqiao, <span class="citation" data-cites="Wei1984">(<a href="#ref-Wei1984" role="doc-biblioref">Wei, Huang, and Zhang 1984</a>)</span>; 2. Liaohe river region, <span class="citation" data-cites="Li1991">(<a href="#ref-Li1991" role="doc-biblioref">C. Li and Xu 1991</a>)</span>; 3. Deshan Second Brick factory, <span class="citation" data-cites="Xi1994">(<a href="#ref-Xi1994" role="doc-biblioref">Xi 1994</a>)</span>; 4. Zhangjiatan, <span class="citation" data-cites="LixianMuseum1992">(<a href="#ref-LixianMuseum1992" role="doc-biblioref">Lixian County Museum 1992</a>)</span>; 5. Huzhua Mount., <span class="citation" data-cites="Tan1999">(<a href="#ref-Tan1999" role="doc-biblioref">Tan 1999</a>)</span>; 6. Fangniu Mount., <span class="citation" data-cites="Fang2002">(<a href="#ref-Fang2002" role="doc-biblioref">Fang et al. 2002</a>)</span>; 7. Fanba, <span class="citation" data-cites="Xia2022Fanba">(<a href="#ref-Xia2022Fanba" role="doc-biblioref">Xia et al. 2022</a>)</span>; 8. Xiaokongshan, <span class="citation" data-cites="XiaokongshanTeam1988">(<a href="#ref-XiaokongshanTeam1988" role="doc-biblioref">Xiaokongshan Joint Excavation Team 1988</a>)</span>; 9. Hejialiang, <span class="citation" data-cites="Wang2014Hanzhong">(<a href="#ref-Wang2014Hanzhong" role="doc-biblioref">S. Wang et al. 2014</a>)</span>; 10. Longgangsi, <span class="citation" data-cites="Lu2006Liangshan">(<a href="#ref-Lu2006Liangshan" role="doc-biblioref">N. Lu, Chinese Academy of Sciences, and Hou 2006</a>)</span>; 11. Shangdan basin, <span class="citation" data-cites="Wang2013Danjiang">(<a href="#ref-Wang2013Danjiang" role="doc-biblioref">S. Wang et al. 2013</a>)</span>; 12. Yaoshi basin, <span class="citation" data-cites="Wang2000Yaoshi">(<a href="#ref-Wang2000Yaoshi" role="doc-biblioref">S. Wang and Hu 2000</a>)</span>; 13. Choushuihe, <span class="citation" data-cites="Dai1973Lantian">(<a href="#ref-Dai1973Lantian" role="doc-biblioref">Dai and Xu 1973</a>)</span>; 14. Kehe, <span class="citation" data-cites="Jia1962Kehe">(<a href="#ref-Jia1962Kehe" role="doc-biblioref">Jia 1962</a>)</span>; 15. Shuigou, <span class="citation" data-cites="Huang1964Sanmenxia">(<a href="#ref-Huang1964Sanmenxia" role="doc-biblioref">Huang 1964</a>)</span>; 16. Hezhigou, <span class="citation" data-cites="Liu1984Jingchuan">(<a href="#ref-Liu1984Jingchuan" role="doc-biblioref">Liu, Huang, and Lin 1984</a>)</span>; 17. Xigou, <span class="citation" data-cites="Jia1959Xigou">(<a href="#ref-Jia1959Xigou" role="doc-biblioref">Jia 1959</a>)</span>; 18. Dingcun, <span class="citation" data-cites="SXA2014Dingcun Tao1984Dingcun">(<a href="#ref-SXA2014Dingcun" role="doc-biblioref">Shanxi Provincial Institute of Archaeology 2014</a>; <a href="#ref-Tao1984Dingcun" role="doc-biblioref">Tao et al. 1984</a>)</span>; 19. Liujiacha, <span class="citation" data-cites="Xie1982Liujiacha">(<a href="#ref-Xie1982Liujiacha" role="doc-biblioref">Xie 1982</a>)</span>; 20. Dangcheng, <span class="citation" data-cites="Wu1989Dangcheng">(<a href="#ref-Wu1989Dangcheng" role="doc-biblioref">Wu and Sun 1989</a>)</span> ; 21. Zhoukoudian Loc.1, <span class="citation" data-cites="NIGPAS1985PekingMan">(<a href="#ref-NIGPAS1985PekingMan" role="doc-biblioref">Nanjing Institute of Geology and Palaeontology, Chinese Academy of Sciences 1985</a>)</span>; 22. Xujiayao, <span class="citation" data-cites="Jia1976Xujayao Jia1979Xujayao Ma2011Xujayao Wang2016Houjiayao">(<a href="#ref-Jia1976Xujayao" role="doc-biblioref">Jia and Wei 1976</a>; <a href="#ref-Jia1979Xujayao" role="doc-biblioref">Jia, Wei, and Li 1979</a>; <a href="#ref-Ma2011Xujayao" role="doc-biblioref">Ma, Pei, and Gao 2011</a>; <a href="#ref-Wang2016Houjiayao" role="doc-biblioref">F. Wang 2016</a>)</span>); 23. Jinsitai, <span class="citation" data-cites="Wang2010Jinstai">(<a href="#ref-Wang2010Jinstai" role="doc-biblioref">X. Wang et al. 2010</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-Spheroids_distribution_China" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Spheroids_distribution_China-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/Spheroids_distribution_China.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Spheroids_distribution_China-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Map of Paleolithic Sites with Spheroids in China and Their Associated Lithic Industries
</figcaption>
</figure>
</div>
</div>
</div>
<p>In China, spheroids constitute a technological category with broad temporal and spatial distribution <span class="citation" data-cites="Yi2012Spheroids">(<a href="#ref-Yi2012Spheroids" role="doc-biblioref">Yi, Gao, and Pei 2012</a>)</span>, as shown in <a href="#fig-Spheroids_distribution_China" class="quarto-xref">Figure&nbsp;11</a>. In addition to the one spheroid collected near the Gongwangling site in Shanxi <span class="citation" data-cites="Dai1973Lantian">(<a href="#ref-Dai1973Lantian" role="doc-biblioref">Dai and Xu 1973</a>)</span>, the earliest dated spheroids originate from Zhoukoudian Locality 1 <span class="citation" data-cites="NIGPAS1985PekingMan">(<a href="#ref-NIGPAS1985PekingMan" role="doc-biblioref">Nanjing Institute of Geology and Palaeontology, Chinese Academy of Sciences 1985</a>)</span>, attributed to the early Middle Pleistocene. In terms of geographic range, the southernmost and westernmost occurrences of spheroids are found at the Mujiaqiao site in Yunnan <span class="citation" data-cites="Wei1984">(<a href="#ref-Wei1984" role="doc-biblioref">Wei, Huang, and Zhang 1984</a>)</span>, while the northernmost spheroids come from the Jinsitai site in Inner Mongolia <span class="citation" data-cites="Wang2010Jinstai">(<a href="#ref-Wang2010Jinstai" role="doc-biblioref">X. Wang et al. 2010</a>)</span>. The widespread occurrence of spheroids across time and space may indicate their role as a generalized or multipurpose tool within Pleistocene contexts, capable of serving diverse functions in varying ecological and cultural settings.</p>
<p>Over 1522 spheroids have been identified across more than 23 archaeological sites or localities in China. However, that many of these findings derive from surface surveys rather than systematic excavations, and the recovered quantities are often limited. Thus, the number of spheroids per site varies considerably: 19 sites have yielded fewer than ten specimens each. By contrast, three sites—Xujiayao, Dingcun, and Jinsitai—have produced substantial assemblages, each exceeding 100 spheroids <span class="citation" data-cites="Wang2016Houjiayao Wang2010Jinstai SXA2014Dingcun">(<a href="#ref-Wang2016Houjiayao" role="doc-biblioref">F. Wang 2016</a>; <a href="#ref-Wang2010Jinstai" role="doc-biblioref">X. Wang et al. 2010</a>; <a href="#ref-SXA2014Dingcun" role="doc-biblioref">Shanxi Provincial Institute of Archaeology 2014</a>)</span>. Notably, the Xujiayao site alone has yielded over 1,000 specimens <span class="citation" data-cites="Wang2016Houjiayao">(<a href="#ref-Wang2016Houjiayao" role="doc-biblioref">F. Wang 2016</a>)</span>.</p>
<p>The raw materials used for spheroids at these archaeological sites primarily include quartz, quartzite, sandstone, and limestone, with occasional occurrences of lava and dolomite at a few localities. Among these, quartz and quartzite are the most widely used materials, found at 18 sites across China. In contrast, spheroids made of sandstone and limestone are mainly concentrated at sites distributed along the Fen River and Li River basins in Central China. Previous researches have observed that the morphological characteristics of spheroids are influenced by the physical properties of the raw materials <span class="citation" data-cites="Tao1984Dingcun">(<a href="#ref-Tao1984Dingcun" role="doc-biblioref">Tao et al. 1984</a>)</span>. For example, at the Dingcun site, spheroids made from quartz tend to be irregular and angular, possibly due to the fragile nature of quartz. In comparison, those made from softer materials such as limestone and sandstone are generally more rounded and smoother, with flake scars that appear more diffuse or less distinct <span class="citation" data-cites="Tao1984Dingcun">(<a href="#ref-Tao1984Dingcun" role="doc-biblioref">Tao et al. 1984</a>)</span>.</p>
<p>Three primary techniques have been identified in the manufacture of spheroids: flaking, involving the removal of flakes to shape the object (e.g., Mujiaqiao, <span class="citation" data-cites="Wei1984">(<a href="#ref-Wei1984" role="doc-biblioref">Wei, Huang, and Zhang 1984</a>)</span>); pecking, where two blanks are struck together to round off edges—sometimes by splitting a cobble and using the halves against each other (e.g., Dingcun, <span class="citation" data-cites="SXA2014Dingcun">(<a href="#ref-SXA2014Dingcun" role="doc-biblioref">Shanxi Provincial Institute of Archaeology 2014</a>)</span>); and battering, involving repeated percussion of a polyhedrons (e.g., Zhoukoudian, <span class="citation" data-cites="NIGPAS1985PekingMan">(<a href="#ref-NIGPAS1985PekingMan" role="doc-biblioref">Nanjing Institute of Geology and Palaeontology, Chinese Academy of Sciences 1985</a>)</span>). Experimental studies suggest that pecking and battering yield similar efficiency and spheroid form <span class="citation" data-cites="Lu2021Spheroids">(<a href="#ref-Lu2021Spheroids" role="doc-biblioref">L. Lu, Dong, and Chen 2021</a>)</span>. Many sites, such as Xujiayao and Dingcun, show evidence of multiple techniques, including combined or sequential methods like pecking after flaking to improve sphericity <span class="citation" data-cites="Tao1984Dingcun NIGPAS1985PekingMan">(<a href="#ref-Tao1984Dingcun" role="doc-biblioref">Tao et al. 1984</a>; <a href="#ref-NIGPAS1985PekingMan" role="doc-biblioref">Nanjing Institute of Geology and Palaeontology, Chinese Academy of Sciences 1985</a>)</span>. No clear relationship has yet been established between raw material types and specific production methods.</p>
<p>At Dingcun and Mujiaqiao, thick, flat cobbles were selected and shaped through peripheral flaking, producing roughly approximately cubic shape <span class="citation" data-cites="Wei1984 Tao1984Dingcun">(<a href="#ref-Wei1984" role="doc-biblioref">Wei, Huang, and Zhang 1984</a>; <a href="#ref-Tao1984Dingcun" role="doc-biblioref">Tao et al. 1984</a>)</span>. Mujiaqiao specimens retain parts of the cortex, while at Dingcun, flakes with large exterior and small interior platform angles were removed from spheroid blank to increase edge angles and enhance sphericity <span class="citation" data-cites="Tao1984Dingcun Wei1984">(<a href="#ref-Tao1984Dingcun" role="doc-biblioref">Tao et al. 1984</a>; <a href="#ref-Wei1984" role="doc-biblioref">Wei, Huang, and Zhang 1984</a>)</span>. Of the six sites exhibiting similar strategies to QSY spehroids, all but Mujiaqiao are located within the Fen River and Lishui River regions. These sites are grouped into the Keheng–Dingcun techno-complexes and Lishui techno-complexes, characterized by large flakes and large triangular points <span class="citation" data-cites="LixianMuseum1992 Tan1999 Fang2002 SXA2014Dingcun Jia1962Kehe">(<a href="#ref-LixianMuseum1992" role="doc-biblioref">Lixian County Museum 1992</a>; <a href="#ref-Tan1999" role="doc-biblioref">Tan 1999</a>; <a href="#ref-Fang2002" role="doc-biblioref">Fang et al. 2002</a>; <a href="#ref-SXA2014Dingcun" role="doc-biblioref">Shanxi Provincial Institute of Archaeology 2014</a>; <a href="#ref-Jia1962Kehe" role="doc-biblioref">Jia 1962</a>)</span>. The large triangular points were produced by striking the dorsal surface of large flakes to concentrate edges at the tip, creating triangular outlines and steep cross-sections—indicative of a deliberate shaping strategy. This is a significant observation, as it implies that spheroid production techniques similar to those at QSY are more frequently associated with lithic assemblages characterized by intentional shaping strategies.</p>
<p>From the perspective of lithic industries represented at spheroid-bearing sites, faceted spheroids are found in both core and flake industry and Middle Paleolithic sites. However, they occur most frequently in Acheulean industries and in traditions of large flake and large triangular point <span class="citation" data-cites="Wang2014Hanzhong Lu2006Liangshan Wang2013Danjiang Wang2000Yaoshi">(<a href="#ref-Wang2014Hanzhong" role="doc-biblioref">S. Wang et al. 2014</a>, <a href="#ref-Wang2013Danjiang" role="doc-biblioref">2013</a>; <a href="#ref-Lu2006Liangshan" role="doc-biblioref">N. Lu, Chinese Academy of Sciences, and Hou 2006</a>; <a href="#ref-Wang2000Yaoshi" role="doc-biblioref">S. Wang and Hu 2000</a>)</span>, both of which are marked by deliberate shaping strategies (<a href="#fig-Spheroids_distribution_China" class="quarto-xref">Figure&nbsp;11</a>). Notably, even sites previously classified as belonging to simple core and flake industries or Mode 1, such as Xujiayao, demonstrate technological capacities that surpass the typical expectations of Mode 1 <span class="citation" data-cites="Wang2016Houjiayao">(<a href="#ref-Wang2016Houjiayao" role="doc-biblioref">F. Wang 2016</a>)</span>.</p>
<p>It should be emphasized, however, that we do not intend to imply a direct association between faceted spheroids and Mode 2 or the Acheulean technology. Rather, we argue that faceted spheroids reflect a complex shaping strategy. Their presence within Acheulean contexts is understandable, as spheroids and LCTs share certain core technological features<span class="citation" data-cites="leakey1971 Cabanes2024 isaac1986foundation">(<a href="#ref-leakey1971" role="doc-biblioref">Leakey 1971</a>; <a href="#ref-Cabanes2024" role="doc-biblioref">Cabanès et al. 2024</a>; <a href="#ref-isaac1986foundation" role="doc-biblioref">Glynn L. Isaac 1986</a>)</span>. When faceted spheroids appear in more rudimentary industries or assemblages, it suggests that conceptual templates and advanced technological capacities were already present within those contexts.</p>
<p>This pattern aligns with spheroid findings in other regions of the world. Early examples of spheroids have been identified in various lithic assemblages across Africa, Europe, the Levant, and Asia, where the associated techno-complexes are generally attributed to either the Acheulean or the Oldowan. Spheroids appear in what is considered the Late Oldowan, if a chronological boundary is set at 2.0 Ma to distinguish between Early and Late Oldowan <span class="citation" data-cites="gallotti2018emergence">(<a href="#ref-gallotti2018emergence" role="doc-biblioref">Gallotti, Mussi, et al. 2018</a>)</span>. The growing recognition of technological diversity within the Oldowan has led to a broader consensus that the Late Oldowan includes signs of innovation, such as more complex flaking patterns and decreased morphological variability in flakes <span class="citation" data-cites="gallotti2018emergence braun2019">(<a href="#ref-gallotti2018emergence" role="doc-biblioref">Gallotti, Mussi, et al. 2018</a>; <a href="#ref-braun2019" role="doc-biblioref">Braun et al. 2019</a>)</span>. Spheroids, we propose here, may represent one of the key indicators of this increasing technological complexity during the Late Oldowan <span class="citation" data-cites="tittonSubspheroidsLithicAssemblage2020">(<a href="#ref-tittonSubspheroidsLithicAssemblage2020" role="doc-biblioref">Titton et al. 2020</a>)</span>. In particular, faceted spheroids, which reflect a deliberate shaping strategy, may indicate a level of technical skill approaching that of the earliest Acheulean—or perhaps even foreshadowing their emergence.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This study provides one of the earliest systematic analyses focused on spheroids from northern China. By applying a range of quantitative methods, we conducted an integrated morphological and technological study of the QSY spheroids. Our results demonstrate that these spheroids were produced through a programmed reduction strategy aimed at achieving standardized spherical forms, primarily using hard-hammer direct percussion. The evidence of shaping strategies on QSY spheroids confirms that they were intentionally made tools with conceptual template rather than exhausted cores. This distinguishes them from polyhedrons or multi-facial cores in their terminal reduction stages. Traditionally, lithic technology in northern China prior to the Late Pleistocene has been considered stagnant and generally classified as simple core-and-flake industries. However, the QSY assemblage from ~429ka clearly reveals a higher level of technological sophistication.</p>
<p>This paper also presents one of the first systematic overviews of the spatial and temporal distribution and technological variability of spheroids within China. We found that Chinese spheroids display considerable diversity in raw materials, production techniques, and morphology. Some assemblages contain spheroids that may be comparable to those from QSY and tend to appear within Acheulean or shaping-oriented techno-complexes, often dated later than QSY. This highlights the particular significance of the QSY spheroids. However, the current dataset remains limited, and many sites lack detailed morphological and technological studies of spheroids, hampering broader inferences about hominin technological behaviors. We therefore emphasize the need for site-specific analysis of spheroids in future research.</p>
<p>Our study employed multiple quantitative methods, including spherical harmonics, some of which are still relatively novel in lithic analysis. These approaches offer useful tools for in-depth spheroid research. Given the limitations of traditional typology in capturing the functional, morphological, and technological variability of spheroids across sites, we argue that multiple method approaches are essential. From the perspective of typology, spheroids have often been dismissed as poor marker of hominin behavior due to their wide spatial and temporal distribution, combined with low-cost technologies, more refined studies increasingly reveal their diversity and potential as markers of homonin technological behavior <span class="citation" data-cites="tittonSubspheroidsLithicAssemblage2020 vaquero2018">(<a href="#ref-tittonSubspheroidsLithicAssemblage2020" role="doc-biblioref">Titton et al. 2020</a>; <a href="#ref-vaquero2018" role="doc-biblioref">Vaquero and Romagnoli 2018</a>)</span>. For example, distinctions between flaking-based and battering-based spheroids—along with patterns of raw material selection, production goals, and associations with specific subsistence strategies or environmental adaptations—may prove meaningful <span class="citation" data-cites="Cabanes2024">(<a href="#ref-Cabanes2024" role="doc-biblioref">Cabanès et al. 2024</a>)</span>. Beyond the methods of morphological and technological analysis used here, future studies incorporating functional analysis and experimental replication will further enhance our understanding.</p>
<p>Lastly, further research should explore the technological connections between faceted spheroids and the Acheulean. As core tools shaped through flaking, spheroids and LCTs may share underlying cognitive and manual skills. Examining their similarities and differences could offer valuable insights into the pathways of technological evolution between Oldowan and Acheulean traditions.</p>
<!-- The following line inserts a page break  -->
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level1">
<h1>References</h1>
<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Van2023" class="csl-entry" role="listitem">
Bavel, Casper van, Wim Thiels, and Rob Jelier. 2023. <span>“Cell Shape Characterization, Alignment, and Comparison Using FlowShape.”</span> <em>Bioinformatics</em> 39 (6): btad383.
</div>
<div id="ref-beyene2013" class="csl-entry" role="listitem">
Beyene, Yonas, Shigehiro Katoh, Giday WoldeGabriel, William K. Hart, Kozo Uto, Masafumi Sudo, Megumi Kondo, et al. 2013. <span>“The Characteristics and Chronology of the Earliest Acheulean at Konso, Ethiopia.”</span> <em>Proceedings of the National Academy of Sciences</em> 110 (5): 1584–91. <a href="https://doi.org/10.1073/pnas.1221285110">https://doi.org/10.1073/pnas.1221285110</a>.
</div>
<div id="ref-braun2019" class="csl-entry" role="listitem">
Braun, David R., Vera Aldeias, Will Archer, J Ramon Arrowsmith, Niguss Baraki, Christopher J. Campisano, Alan L. Deino, et al. 2019. <span>“Earliest Known Oldowan Artifacts at &gt;2.58 Ma from Ledi-Geraru, Ethiopia, Highlight Early Technological Diversity.”</span> <em>Proceedings of the National Academy of Sciences</em> 116 (24): 11712–17. <a href="https://doi.org/10.1073/pnas.1820177116">https://doi.org/10.1073/pnas.1820177116</a>.
</div>
<div id="ref-Cabanes2024" class="csl-entry" role="listitem">
Cabanès, Julia, Antony Borel, Javier Baena Preysler, Antoine Lourdeau, Dominique Cliquet, David Colonge, and Marie-Hélène Moncel. 2024. <span>“Exploring the Technological and Functional Diversity of Polyhedrons, Spheroids and Bolas: An Integrated and Comparative Analysis of Cases from France and North Africa.”</span> <em>Journal of Paleolithic Archaeology</em> 7 (1): 30. <a href="https://doi.org/10.1007/s41982-024-00195-x">https://doi.org/10.1007/s41982-024-00195-x</a>.
</div>
<div id="ref-clark1955" class="csl-entry" role="listitem">
Clark, J. D. 1955. <span>“The Stone Ball: Its Associations and Use by Prehistoric Man in Africa.”</span> In <em>II Congr<span>è</span>s Panafricain de Pr<span>é</span>histoire, Alger. Actes de La IIe Session</em>, edited by L. Balout, 403–17. Paris: Arts et M<span>é</span>tiers Graphiques.
</div>
<div id="ref-clarksonMeasuringCoreReduction2013" class="csl-entry" role="listitem">
Clarkson, Chris. 2013. <span>“Measuring Core Reduction Using 3D Flake Scar Density: A Test Case of Changing Core Reduction at Klasies River Mouth, South Africa.”</span> <em>Journal Of Archaeological Science</em> 40 (12): 4348–57.
</div>
<div id="ref-Dai1973Lantian" class="csl-entry" role="listitem">
Dai, Erjian, and Chunhua Xu. 1973. <span>“New Paleolithic Materials and the Lantian Man Culture.”</span> <em>Kaogu Xuebao (Acta Archaeologica Sinica)</em>, no. 2: 14.
</div>
<div id="ref-delatorre2004" class="csl-entry" role="listitem">
De La Torre, Ignacio. 2004. <span>“Omo Revisited: Evaluating the Technological Skills of Pliocene Hominids.”</span> <em>Current Anthropology</em> 45 (4): 439–65. <a href="https://doi.org/10.1086/422079">https://doi.org/10.1086/422079</a>.
</div>
<div id="ref-deweyer2017" class="csl-entry" role="listitem">
De Weyer, Louis. 2017. <span>“An Early Stone Age in Western Africa? Spheroids and Polyhedrons at Ounjougou, Mali.”</span> <em>Journal of Lithic Studies</em> 4 (1). <a href="https://doi.org/10.2218/jls.v4i1.1682">https://doi.org/10.2218/jls.v4i1.1682</a>.
</div>
<div id="ref-duke2021" class="csl-entry" role="listitem">
Duke, Hilary, Craig Feibel, and Sonia Harmand. 2021. <span>“Before the Acheulean: The Emergence of Bifacial Shaping at Kokiselei 6 (1.8 Ma), West Turkana, Kenya.”</span> <em>Journal of Human Evolution</em> 159: 103061.
</div>
<div id="ref-Eerkens2001" class="csl-entry" role="listitem">
Eerkens, Jelmer W., and Robert L. Bettinger. 2001. <span>“Techniques for Assessing Standardization in Artifact Assemblages: Can We Scale Material Variability?”</span> <em>American Antiquity</em> 66 (3): 493–504. <a href="https://doi.org/10.2307/2694247">https://doi.org/10.2307/2694247</a>.
</div>
<div id="ref-Fang2002" class="csl-entry" role="listitem">
Fang, Yingsan, Jiehua Wang, Renyou Liang, Juxiang Wang, Zhonghua Zhai, and Chun Yang. 2002. <span>“Paleolithic Artifacts Discovered at Fangniushan, Jurong County, Jiangsu Province.”</span> <em>Acta Anthropologica Sinica</em> 21 (1): 41–49.
</div>
<div id="ref-gallotti2018emergence" class="csl-entry" role="listitem">
Gallotti, Rosalia, Margherita Mussi, et al. 2018. <span>“The Emergence of the Acheulean in East Africa and Beyond.”</span> <em>Speringer, Cham</em>.
</div>
<div id="ref-Grieb2022" class="csl-entry" role="listitem">
Grieb, Jonas, Inés Barbero-García, and José Luis Lerma. 2022. <span>“Spherical Harmonics to Quantify Cranial Asymmetry in Deformational Plagiocephaly.”</span> <em>Scientific Reports</em> 12 (1): 167. <a href="https://doi.org/10.1038/s41598-021-04181-z">https://doi.org/10.1038/s41598-021-04181-z</a>.
</div>
<div id="ref-Harper2022" class="csl-entry" role="listitem">
Harper, Christine M, Deanna M Goldstein, and Adam D Sylvester. 2022. <span>“Comparing and Combining Sliding Semilandmarks and Weighted Spherical Harmonics for Shape Analysis.”</span> <em>Journal of Anatomy</em> 240 (4): 678–87.
</div>
<div id="ref-Hewitt2024" class="csl-entry" role="listitem">
Hewitt, Madeleine N., Iván A. Cruz, Tor H. Linbo, and David W. Raible. 2024. <span>“Spherical Harmonics Analysis Reveals Cell Shape-Fate Relationships in Zebrafish Lateral Line Neuromasts.”</span> <em>Development</em> 151 (2): dev202251. <a href="https://doi.org/10.1242/dev.202251">https://doi.org/10.1242/dev.202251</a>.
</div>
<div id="ref-Huang1964Sanmenxia" class="csl-entry" role="listitem">
Huang, Weiwen. 1964. <span>“Paleolithic Artifacts from the Sanmenxia Region in Western Henan.”</span> <em>Vertebrata PalAsiatica</em>, no. 2: 66–85.
</div>
<div id="ref-inizan1999" class="csl-entry" role="listitem">
Inizan, Marie-Louise, Marie Reduron-Ballinger, and Hélène Roche. 1999. <em>Technology and Terminology of Knapped Stone</em>. 5th ed. Nanterre: Cercle de Recherches et d’Études Préhistoriques.
</div>
<div id="ref-Isaac1981" class="csl-entry" role="listitem">
Isaac, G. L. 1981. <span>“Stone Age Visiting Cards: Approaches to the Study of Early Landuse Patterns.”</span> In <em>Pattern of the Past: Studies in Honour of David Clarke</em>, edited by I. Hodder, G. Isaac, and N. Hammond, 131–55. Cambridge: Cambridge University Press.
</div>
<div id="ref-Isaac1986" class="csl-entry" role="listitem">
———. 1986. <span>“Foundation Stones: Early Artifacts as Indicators of Activities and Abilities.”</span> In <em>Stone Age Prehistory: Studies in Memory of Charles McBurney</em>, edited by G. N. Bailey and P. Callow, 221–41. Cambridge: Cambridge University Press.
</div>
<div id="ref-isaac1986foundation" class="csl-entry" role="listitem">
Isaac, Glynn L. 1986. <span>“Foundation Stones: Early Artefacts as Indicators of Activities and Abilities.”</span> <em>Stone Age Prehistory: Studies in Memory of Charles McBurney</em>, 221–41.
</div>
<div id="ref-Jia1959Xigou" class="csl-entry" role="listitem">
Jia, Lanpo. 1959. <span>“A Paleolithic Cultural Site at Xigou, Licun, Quwo County, Shanxi Province.”</span> <em>Kaogu (Archaeology)</em>, no. 1: 6.
</div>
<div id="ref-Jia1962Kehe" class="csl-entry" role="listitem">
———. 1962. <em>Kehe: An Early Paleolithic Cultural Site in Southwestern Shanxi</em>. Science Press.
</div>
<div id="ref-Jia1976Xujayao" class="csl-entry" role="listitem">
Jia, Lanpo, and Qi Wei. 1976. <span>“The Paleolithic Cultural Site of Xujayao, Yanggao.”</span> <em>Kaogu Xuebao (Acta Archaeologica Sinica)</em>, no. 2: 24.
</div>
<div id="ref-Jia1979Xujayao" class="csl-entry" role="listitem">
Jia, Lanpo, Qi Wei, and Chaorong Li. 1979. <span>“Excavation Report of the Xujayao Paleolithic Cultural Site in 1976.”</span> <em>Vertebrata PalAsiatica</em>, no. 4: 17–33, 87–90.
</div>
<div id="ref-jones1994" class="csl-entry" role="listitem">
Jones, Peter R et al. 1994. <span>“Results of Experimental Work in Relation to the Stone Industries of Olduvai Gorge.”</span> <em>Olduvai Gorge</em> 5: 1968–71.
</div>
<div id="ref-kleindienst1962" class="csl-entry" role="listitem">
Kleindienst, Maxine R. 1962. <span>“Components of the East African Acheulian Assemblage: An Analytic Approach.”</span> In <em>Actes Du IVeme Congres Panafricain de Pr<span>é</span>histoire Et de l’<span>é</span>tude Du Quaternaire</em>, 40:81–105. Mus<span>é</span>e royal de l’Afrique centrale Tervuren.
</div>
<div id="ref-leakey1971" class="csl-entry" role="listitem">
Leakey, Mary D. 1971. <em>Olduvai Gorge, Vol. 3: Excavations in Beds i and II, 1960–1963</em>. Cambridge: Cambridge University Press.
</div>
<div id="ref-leakey1979" class="csl-entry" role="listitem">
———. 1979. <em>Olduvai Gorge: My Search for Early Man</em>. London: William Collins.
</div>
<div id="ref-Li1991" class="csl-entry" role="listitem">
Li, Chaorong, and Changqing Xu. 1991. <span>“Paleolithic Artifacts Discovered at the Liao River in Anyi, Jiangxi, and Their Significance.”</span> <em>Acta Anthropologica Sinica</em> 10 (1): 8.
</div>
<div id="ref-li2000" class="csl-entry" role="listitem">
Li, Rongquan, Jianguo Qiao, Weili Qiu, Qiumin Zhai, and Yongliang Li. 2000. <span>“Soluble Salt Deposit in the Nihewan Beds and Its Environmental Significance.”</span> <em>Science in China Series D: Earth Sciences</em> 43: 464–79.
</div>
<div id="ref-lin2024" class="csl-entry" role="listitem">
Lin, Sam C. 2024. <span>“A New Method for Quantifying Flake Scar Organisation on Cores Using Orientation Statistics.”</span> <em>Journal of Archaeological Science</em>.
</div>
<div id="ref-Link2024" class="csl-entry" role="listitem">
Link, Rabea, Mona Jaggy, Martin Bastmeyer, and Ulrich S Schwarz. 2024. <span>“Modelling Cell Shape in 3D Structured Environments: A Quantitative Comparison with Experiments.”</span> <em>PLOS Computational Biology</em> 20 (4): e1011412.
</div>
<div id="ref-Liu1984Jingchuan" class="csl-entry" role="listitem">
Liu, Yulin, Weiwen Huang, and Yipu Lin. 1984. <span>“Human Fossils and Paleolithic Artifacts Discovered in Jingchuan, Gansu Province.”</span> <em>Acta Anthropologica Sinica</em>, no. 1: 11.
</div>
<div id="ref-LixianMuseum1992" class="csl-entry" role="listitem">
Lixian County Museum. 1992. <span>“A Brief Report on the Paleolithic Localities at Zhangjiatan and Xiangong in Lixian, Hunan Province.”</span> <em>Huaxia Archaeology</em>, no. 4: 8.
</div>
<div id="ref-Lu2021Spheroids" class="csl-entry" role="listitem">
Lu, Liqun, Bing Dong, and Shengqian Chen. 2021. <span>“An Experimental Study on Stone Spheroids from the Paleolithic Period in China.”</span> <em>Acta Anthropologica Sinica</em> 40 (4): 13.
</div>
<div id="ref-Lu2006Liangshan" class="csl-entry" role="listitem">
Lu, Na, Graduate School of the Chinese Academy of Sciences, and Yamei Hou. 2006. <span>“Analysis and Comparative Study of Lithic Manufacturing Patterns at the Liangshan Site.”</span> In <em>Annual Meeting of the Vertebrate Paleontology Section, Palaeontological Society of China</em>.
</div>
<div id="ref-Ma2011Xujayao" class="csl-entry" role="listitem">
Ma, Ning, Shuwen Pei, and Xing Gao. 2011. <span>“Study of Lithic Artifacts Excavated from Locality 74093 at the Xujayao Site in 1977.”</span> <em>Acta Anthropologica Sinica</em> 30 (3): 14.
</div>
<div id="ref-Medyukhina2020" class="csl-entry" role="listitem">
Medyukhina, Anna, Marco Blickensdorf, Zoltán Cseresnyés, Nora Ruef, Jens V Stein, and Marc Thilo Figge. 2020. <span>“Dynamic Spherical Harmonics Approach for Shape Classification of Migrating Cells.”</span> <em>Scientific Reports</em> 10 (1): 6072.
</div>
<div id="ref-mora2005" class="csl-entry" role="listitem">
Mora, Rafael, and Ignacio De La Torre. 2005. <span>“Percussion Tools in Olduvai Beds I and II (Tanzania): Implications for Early Human Activities.”</span> <em>Journal of Anthropological Archaeology</em> 24 (2): 179–92. <a href="https://doi.org/10.1016/j.jaa.2004.12.001">https://doi.org/10.1016/j.jaa.2004.12.001</a>.
</div>
<div id="ref-Muller2023" class="csl-entry" role="listitem">
Muller, Antoine, Deborah Barsky, Robert Sala-Ramos, Gonen Sharon, Stefania Titton, Josep-Maria Vergès, and Leore Grosman. 2023. <span>“The Limestone Spheroids of ‘Ubeidiya: Intentional Imposition of Symmetric Geometry by Early Hominins?”</span> <em>Royal Society Open Science</em> 10 (9): 230671.
</div>
<div id="ref-muller2023" class="csl-entry" role="listitem">
Muller, Antoine, and Chris Clarkson. 2023. <span>“Filling in the Blanks: Standardization of Lithic Flake Production Throughout the Stone Age.”</span> <em>Lithic Technology</em> 48 (3): 222–36. <a href="https://doi.org/10.1080/01977261.2022.2103290">https://doi.org/10.1080/01977261.2022.2103290</a>.
</div>
<div id="ref-mussi2025" class="csl-entry" role="listitem">
Mussi, Margherita. 2025. <span>“The Volcanic Rock Spheres of Melka Kunture (Upper Awash, Ethiopia) at Gombore IB and Later Acheulean Sites.”</span> <em>Quaternary International</em> 721 (March): 109681. <a href="https://doi.org/10.1016/j.quaint.2025.109681">https://doi.org/10.1016/j.quaint.2025.109681</a>.
</div>
<div id="ref-NIGPAS1985PekingMan" class="csl-entry" role="listitem">
Nanjing Institute of Geology and Palaeontology, Chinese Academy of Sciences. 1985. <em>Palaeontologia Sinica, Whole Volume No. 168, New Series d, No. 12: A Study of Peking Man’s Lithic Artifacts</em>. Science Press.
</div>
<div id="ref-Noshita2025" class="csl-entry" role="listitem">
Noshita, Koji, Tomomi Nakagawa, Akihiro Kaneda, Kohei Tamura, and Hisashi Nakao. 2025. <span>“The Cultural Transmission of Ongagawa Style Pottery in the Prehistoric Japan: Quantitative Analysis on Three-Dimensional Data of Archaeological Pottery in the Early Yayoi Period.”</span> <em>Journal of the Royal Society Interface</em> 22 (223): 20240889.
</div>
<div id="ref-pei2019" class="csl-entry" role="listitem">
Pei, Shuwen, Chenglong Deng, Ignacio De La Torre, Zhenxiu Jia, Dongdong Ma, Xiaoli Li, and Xiaomin Wang. 2019. <span>“Magnetostratigraphic and Archaeological Records at the Early Pleistocene Site Complex of Madigou (Nihewan Basin): Implications for Human Adaptations in North China.”</span> <em>Palaeogeography, Palaeoclimatology, Palaeoecology</em> 530 (September): 176–89. <a href="https://doi.org/10.1016/j.palaeo.2019.05.014">https://doi.org/10.1016/j.palaeo.2019.05.014</a>.
</div>
<div id="ref-pei2002" class="csl-entry" role="listitem">
Pei, Shuwen, and Yamei Hou. 2002. <span>“Preliminary Study on Raw Materials Exploitation at Donggutuo Site, Nihewan Basin, North China.”</span> <em>Acta Anthropologica Sinica</em> 21 (Suppl.): 53–66.
</div>
<div id="ref-pei2017" class="csl-entry" role="listitem">
Pei, Shuwen, Fei Xie, Chenglong Deng, Zhenxiu Jia, Xiaomin Wang, Ying Guan, Xiaoli Li, Dongdong Ma, and Ignacio De La Torre. 2017. <span>“Early Pleistocene Archaeological Occurrences at the Feiliang Site, and the Archaeology of Human Origins in the Nihewan Basin, North China.”</span> Edited by Dong Hoon Shin. <em>PLOS ONE</em> 12 (11): e0187251. <a href="https://doi.org/10.1371/journal.pone.0187251">https://doi.org/10.1371/journal.pone.0187251</a>.
</div>
<div id="ref-sahnouni1997" class="csl-entry" role="listitem">
Sahnouni, Mohamed, Kathy Schick, and Nicholas Toth. 1997. <span>“An Experimental Investigation into the Nature of Faceted Limestone <span>“</span>Spheroids<span>”</span> in the Early Palaeolithic.”</span> <em>Journal of Archaeological Science</em> 24 (8): 701–13. <a href="https://doi.org/10.1006/jasc.1996.0152">https://doi.org/10.1006/jasc.1996.0152</a>.
</div>
<div id="ref-schick1994" class="csl-entry" role="listitem">
Schick, Kathy D., and Nicholas Toth. 1994. <span>“Early Stone Age Technology in Africa: A Review and Case Study into the Nature and Function of Spheroids and Subspheroids.”</span> In <em>Integrative Paths to the Past: Paleoanthropological Advances in Honor of f. Clark Howell</em>, edited by R. S. Corruccini and R. L. Ciochon, 429–49. New Jersey: Prentice Hall.
</div>
<div id="ref-SXA2014Dingcun" class="csl-entry" role="listitem">
Shanxi Provincial Institute of Archaeology. 2014. <em>The Dingcun Paleolithic Site Complex: Excavation Report of the Dingcun Sites (1976–1980)</em>. Cultural Relics Publishing House.
</div>
<div id="ref-stout2015" class="csl-entry" role="listitem">
Stout, Dietrich, Erin Hecht, Nada Khreisheh, Bruce Bradley, and Thierry Chaminade. 2015. <span>“Cognitive Demands of Lower Paleolithic Toolmaking.”</span> Edited by Nuno Bicho. <em>PLOS ONE</em> 10 (4): e0121804. <a href="https://doi.org/10.1371/journal.pone.0121804">https://doi.org/10.1371/journal.pone.0121804</a>.
</div>
<div id="ref-Tan1999" class="csl-entry" role="listitem">
Tan, Yuanhui. 1999. <span>“A Report on the Paleolithic Locality on the Northern Slope of Huzhua Mountain.”</span> <em>Hunan Archaeological Journal</em>, no. 1: 15.
</div>
<div id="ref-Tao1984Dingcun" class="csl-entry" role="listitem">
Tao, Fuhai, Ziming Liang, Xixiang Xie, Zigui Yin, Wuxu Ding, Wenliang Hu, Shengyue Ding, Fengyun Yang, Linsheng Yin, and Xiaoyong Xie. 1984. <span>“Excavation Report of Locality 80:01 at the Dingcun Paleolithic Site.”</span> <em>Prehistoric Research</em>, no. 2: 57–68.
</div>
<div id="ref-texier2014" class="csl-entry" role="listitem">
Texier, Pierre-Jean, and Helene Roche. 2014. <span>“Poly<span>è</span>dre, Sub-Sph<span>é</span>ro<span>ı̈</span>de, Sph<span>é</span>ro<span>ı̈</span>de Et Bola: Des Segments Plus Ou Moins Longs d’une m<span>ê</span>me Cha<span>ı̂</span>ne Op<span>é</span>ratoire.”</span> <em>Cahier Noir</em>, no. 7: 31–40.
</div>
<div id="ref-tittonSubspheroidsLithicAssemblage2020" class="csl-entry" role="listitem">
Titton, Stefania, Deborah Barsky, Amèlia Bargalló, Alexia Serrano-Ramos, Josep Maria Vergès, Isidro Toro-Moyano, Robert Sala-Ramos, José García Solano, and Juan Manuel Jimenez Arenas. 2020. <span>“Subspheroids in the Lithic Assemblage of Barranco León (Spain): Recognizing the Late Oldowan in Europe.”</span> <em>PLOS ONE</em> 15 (1): e0228290. <a href="https://doi.org/10.1371/journal.pone.0228290">https://doi.org/10.1371/journal.pone.0228290</a>.
</div>
<div id="ref-de2018oldowan" class="csl-entry" role="listitem">
Torre, Ignacio de la, and Rafael Mora. 2018. <span>“Oldowan Technological Behaviour at HWK EE (Olduvai Gorge, Tanzania).”</span> <em>Journal of Human Evolution</em> 120: 236–73.
</div>
<div id="ref-vaquero2018" class="csl-entry" role="listitem">
Vaquero, Manuel, and Francesca Romagnoli. 2018. <span>“Searching for Lazy People: The Significance of Expedient Behavior in the Interpretation of Paleolithic Assemblages.”</span> <em>Journal of Archaeological Method and Theory</em> 25 (2): 334–67. <a href="https://doi.org/10.1007/s10816-017-9339-x">https://doi.org/10.1007/s10816-017-9339-x</a>.
</div>
<div id="ref-Wadell1935" class="csl-entry" role="listitem">
Wadell, Hakon. 1935. <span>“Volume, <span>Shape</span>, and <span>Roundness</span> of <span>Quartz</span> <span>Particles</span>.”</span> <em>The Journal of Geology</em> 43 (3): 250–80. <a href="https://doi.org/10.1086/624298">https://doi.org/10.1086/624298</a>.
</div>
<div id="ref-Wang2016Houjiayao" class="csl-entry" role="listitem">
Wang, Fagang. 2016. <span>“Comprehensive Study of the Houjiayao Site.”</span> Ph.D. dissertation, Hebei Normal University.
</div>
<div id="ref-Wang2000Yaoshi" class="csl-entry" role="listitem">
Wang, Shejiang, and Songmei Hu. 2000. <span>“Paleolithic Artifacts from the Yaoshi Basin, Upper Danjiang River.”</span> <em>Kaogu Yu Wenwu (Archaeology and Cultural Relics)</em>, no. 4: 7.
</div>
<div id="ref-Wang2014Hanzhong" class="csl-entry" role="listitem">
Wang, Shejiang, Xuefeng Sun, Huayu Lu, Shuangwen Yi, Gaike Zhang, Luda Xing, Haixin Zhuo, Kaifeng Yu, and Wei Wang. 2014. <span>“Newly Discovered Paleolithic Artifacts and Their Chronology in the Upper Han River and Hanzhong Basin.”</span> <em>Acta Anthropologica Sinica</em>.
</div>
<div id="ref-Wang2013Danjiang" class="csl-entry" role="listitem">
Wang, Shejiang, Xiaobing Zhang, Huayu Lu, and et al. 2013. <span>“Newly Discovered Paleolithic Artifacts and Their Buried Loess Strata in the Shangdan Basin, Upper Danjiang River.”</span> <em>Acta Anthropologica Sinica</em> 32 (4): 421–31.
</div>
<div id="ref-Wang2010Jinstai" class="csl-entry" role="listitem">
Wang, Xiaokun, Jian Wei, Quanjia Chen, Zhuowei Tang, and Chunxue Wang. 2010. <span>“Excavation Report of the Jinstai Cave Site, Inner Mongolia.”</span> <em>Acta Anthropologica Sinica</em>, no. 1: 18.
</div>
<div id="ref-Wei1984" class="csl-entry" role="listitem">
Wei, Qi, Weiwen Huang, and Xingyong Zhang. 1984. <span>“Newly Discovered Paleolithic Artifacts at Mujiaqiao, Lijiang.”</span> <em>Acta Anthropologica Sinica</em>, no. 3: 11.
</div>
<div id="ref-willoughby1985" class="csl-entry" role="listitem">
Willoughby, Pamela R. 1985. <span>“Spheroids and Battered Stones in the African Early Stone Age.”</span> <em>World Archaeology</em> 17 (1): 44–60. <a href="https://doi.org/10.1080/00438243.1985.9979949">https://doi.org/10.1080/00438243.1985.9979949</a>.
</div>
<div id="ref-Wu1989Dangcheng" class="csl-entry" role="listitem">
Wu, Zhiqing, and Bingliang Sun. 1989. <span>“Preliminary Study of the Paleolithic Cave Site Complex at Dangcheng, Heshun County, Shanxi Province.”</span> <em>Acta Anthropologica Sinica</em> 8 (1): 12.
</div>
<div id="ref-wynn1995" class="csl-entry" role="listitem">
Wynn, Thomas. 1995. <span>“Handaxe Enigmas.”</span> <em>World Archaeology</em> 27 (1): 10–24.
</div>
<div id="ref-Xi1994" class="csl-entry" role="listitem">
Xi, Daohe. 1994. <span>“A Report on the Paleolithic Survey in the Lower Reaches of the Yuan River.”</span> <em>Hunan Archaeological Journal</em>, no. 1: 6.
</div>
<div id="ref-Xia2022Fanba" class="csl-entry" role="listitem">
Xia, Wenting, Shejiang Wang, Xianyan Wang, Huayu Lu, Nan Xia, Gaike Zhang, Jingjing Bie, Xun Yang, and Jiang Wu. 2022. <span>“A Study of the Lithic Artifacts from the Paleolithic Locality at Fanba, Yangxian, Hanzhong Basin.”</span> <em>Acta Anthropologica Sinica</em> 41 (3): 13.
</div>
<div id="ref-XiaokongshanTeam1988" class="csl-entry" role="listitem">
Xiaokongshan Joint Excavation Team. 1988. <span>“Excavation Report of the Xiaokongshan Paleolithic Site in Nanzhao, Henan, in 1987.”</span> <em>Huaxia Archaeology</em>, no. 4: 15.
</div>
<div id="ref-Xie1982Liujiacha" class="csl-entry" role="listitem">
Xie, Junyi. 1982. <span>“The Paleolithic Site at Liujiacha, Huan County, Gansu Province.”</span> <em>Kaogu Xuebao (Acta Archaeologica Sinica)</em>, no. 1: 16.
</div>
<div id="ref-yang2020" class="csl-entry" role="listitem">
Yang, Shi-Xia, Cheng-Long Deng, Ri-Xiang Zhu, and Michael D. Petraglia. 2020. <span>“The Paleolithic in the Nihewan Basin, China: Evolutionary History of an Early to Late Pleistocene Record in Eastern Asia.”</span> <em>Evolutionary Anthropology: Issues, News, and Reviews</em> 29 (3): 125–42. <a href="https://doi.org/10.1002/evan.21813">https://doi.org/10.1002/evan.21813</a>.
</div>
<div id="ref-yang2017" class="csl-entry" role="listitem">
Yang, Shi-Xia, Michael D. Petraglia, Ya-Mei Hou, Jian-Ping Yue, Cheng-Long Deng, and Ri-Xiang Zhu. 2017. <span>“The Lithic Assemblages of Donggutuo, Nihewan Basin: Knapping Skills of Early Pleistocene Hominins in North China.”</span> Edited by William Oki Wong. <em>PLOS ONE</em> 12 (9): e0185101. <a href="https://doi.org/10.1371/journal.pone.0185101">https://doi.org/10.1371/journal.pone.0185101</a>.
</div>
<div id="ref-ye2024" class="csl-entry" role="listitem">
Ye, Zhi, Shuwen Pei, Hua Tu, Yuwei Du, Dongdong Ma, Hao Li, Jingyue Xu, et al. 2024. <span>“26Al/10Be Burial Dating and Technological Strategies of Hominins at the Jijiazhuang Paleolithic Site, Nihewan Basin, China: Implications for Understanding Middle Pleistocene Human Adaptations in East Asia.”</span> <em>Quaternary Science Reviews</em> 339: 108837.
</div>
<div id="ref-Yi2012Spheroids" class="csl-entry" role="listitem">
Yi, Mingjie, Xing Gao, and Shuwen Pei. 2012. <span>“A Preliminary Analysis of the Definition, Classification, and Function of Stone Spheroids.”</span> <em>Acta Anthropologica Sinica</em> 31 (4): 9.
</div>
<div id="ref-yuan2009" class="csl-entry" role="listitem">
Yuan, BY, HW Tong, RL Wen, and YH Wang. 2009. <span>“The Formation Mechanism of the Nihewan Paleo-Lake and Its Relationship with Living Environment for Early Ancient Human.”</span> <em>Journal of Geomechanics</em> 15 (1): 77–87.
</div>
<div id="ref-yuwei2023" class="csl-entry" role="listitem">
Yuwei, DU, ZHANG Yue, YE Zhi, and PEI Shuwen. 2023. <span>“A Taphonomic Analysis of Faunal Remains from the Jijiazhuang Paleolithic Site in the Yuxian Basin.”</span> <em>Acta Anthropologica Sinica</em> 42 (03): 359.
</div>
<div id="ref-zhu2001" class="csl-entry" role="listitem">
Zhu, R. X., K. A. Hoffman, R. Potts, C. L. Deng, Y. X. Pan, B. Guo, C. D. Shi, et al. 2001. <span>“Earliest Presence of Humans in Northeast Asia.”</span> <em>Nature</em> 413 (6854): 413–17. <a href="https://doi.org/10.1038/35096551">https://doi.org/10.1038/35096551</a>.
</div>
<div id="ref-zhu2004" class="csl-entry" role="listitem">
Zhu, R. X., R. Potts, F. Xie, K. A. Hoffman, C. L. Deng, C. D. Shi, Y. X. Pan, et al. 2004. <span>“New Evidence on the Earliest Human Presence at High Northern Latitudes in Northeast Asia.”</span> <em>Nature</em> 431 (7008): 559–62. <a href="https://doi.org/10.1038/nature02829">https://doi.org/10.1038/nature02829</a>.
</div>
</div>
<div style="page-break-after: always;"></div>
<section id="colophon" class="level3">
<h3 class="anchored" data-anchor-id="colophon">Colophon</h3>
<p>This report was generated on 2025-07-10 17:17:20.20016 using the following computational environment and dependencies:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># which R packages and versions?</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="st">"devtools"</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()) devtools<span class="sc">::</span><span class="fu">session_info</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.3 (2025-02-28 ucrt)
 os       Windows 11 x64 (build 26100)
 system   x86_64, mingw32
 ui       RTerm
 language (EN)
 collate  Chinese (Simplified)_China.utf8
 ctype    Chinese (Simplified)_China.utf8
 tz       America/Los_Angeles
 date     2025-07-10
 pandoc   3.2 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
 quarto   NA @ C:\\PROGRA~1\\RStudio\\RESOUR~1\\app\\bin\\quarto\\bin\\quarto.exe

─ Packages ───────────────────────────────────────────────────────────────────
 package      * version  date (UTC) lib source
 abind          1.4-8    2024-09-12 [1] CRAN (R 4.4.1)
 ash            1.0-15   2015-09-01 [1] CRAN (R 4.4.0)
 backports      1.5.0    2024-05-23 [1] CRAN (R 4.4.0)
 base64enc      0.1-3    2015-07-28 [1] CRAN (R 4.4.0)
 bayesm         3.1-6    2023-09-23 [1] CRAN (R 4.4.3)
 bit            4.6.0    2025-03-06 [1] CRAN (R 4.4.3)
 bit64          4.6.0-1  2025-01-16 [1] CRAN (R 4.4.3)
 boot           1.3-31   2024-08-28 [2] CRAN (R 4.4.3)
 broom          1.0.8    2025-03-28 [1] CRAN (R 4.4.3)
 cachem         1.1.0    2024-05-16 [1] CRAN (R 4.4.3)
 car            3.1-3    2024-09-27 [1] CRAN (R 4.4.3)
 carData        3.0-5    2022-01-06 [1] CRAN (R 4.4.3)
 cellranger     1.1.0    2016-07-27 [1] CRAN (R 4.4.3)
 checkmate      2.3.2    2024-07-29 [1] CRAN (R 4.4.3)
 circular     * 0.5-1    2024-08-29 [1] CRAN (R 4.4.3)
 cli            3.6.4    2025-02-13 [1] CRAN (R 4.4.3)
 cluster        2.1.8    2024-12-11 [2] CRAN (R 4.4.3)
 colorspace     2.1-1    2024-07-26 [1] CRAN (R 4.4.3)
 compositions   2.0-8    2024-01-31 [1] CRAN (R 4.4.3)
 crayon         1.5.3    2024-06-20 [1] CRAN (R 4.4.3)
 data.table   * 1.17.0   2025-02-22 [1] CRAN (R 4.4.3)
 DEoptimR       1.1-3-1  2024-11-23 [1] CRAN (R 4.4.2)
 devtools       2.4.5    2022-10-11 [1] CRAN (R 4.4.3)
 digest         0.6.37   2024-08-19 [1] CRAN (R 4.4.3)
 dplyr        * 1.1.4    2023-11-17 [1] CRAN (R 4.4.3)
 ellipsis       0.3.2    2021-04-29 [1] CRAN (R 4.4.3)
 evaluate       1.0.3    2025-01-10 [1] CRAN (R 4.4.3)
 extrafont      0.19     2023-01-18 [1] CRAN (R 4.4.0)
 extrafontdb    1.0      2012-06-11 [1] CRAN (R 4.4.0)
 farver         2.1.2    2024-05-13 [1] CRAN (R 4.4.3)
 fastmap        1.2.0    2024-05-15 [1] CRAN (R 4.4.3)
 forcats      * 1.0.0    2023-01-29 [1] CRAN (R 4.4.3)
 foreign        0.8-88   2025-01-12 [2] CRAN (R 4.4.3)
 Formula        1.2-5    2023-02-24 [1] CRAN (R 4.4.0)
 fs             1.6.5    2024-10-30 [1] CRAN (R 4.4.3)
 generics       0.1.3    2022-07-05 [1] CRAN (R 4.4.3)
 ggalt        * 0.4.0    2017-02-15 [1] CRAN (R 4.4.3)
 ggcorrplot   * 0.1.4.1  2023-09-05 [1] CRAN (R 4.4.3)
 ggplot2      * 3.5.2    2025-04-09 [1] CRAN (R 4.4.3)
 ggpubr       * 0.6.0    2023-02-10 [1] CRAN (R 4.4.3)
 ggrepel      * 0.9.6    2024-09-07 [1] CRAN (R 4.4.3)
 ggsignif       0.6.4    2022-10-13 [1] CRAN (R 4.4.3)
 ggtern       * 3.5.0    2024-03-24 [1] CRAN (R 4.4.3)
 glue           1.8.0    2024-09-30 [1] CRAN (R 4.4.3)
 gridExtra      2.3      2017-09-09 [1] CRAN (R 4.4.3)
 gtable         0.3.6    2024-10-25 [1] CRAN (R 4.4.3)
 here         * 1.0.1    2020-12-13 [1] CRAN (R 4.4.3)
 hexbin         1.28.5   2024-11-13 [1] CRAN (R 4.4.3)
 Hmisc        * 5.2-3    2025-03-16 [1] CRAN (R 4.4.3)
 hms            1.1.3    2023-03-21 [1] CRAN (R 4.4.3)
 htmlTable      2.4.3    2024-07-21 [1] CRAN (R 4.4.3)
 htmltools      0.5.8.1  2024-04-04 [1] CRAN (R 4.4.3)
 htmlwidgets    1.6.4    2023-12-06 [1] CRAN (R 4.4.3)
 httpuv         1.6.16   2025-04-16 [1] CRAN (R 4.4.3)
 jsonlite       2.0.0    2025-03-27 [1] CRAN (R 4.4.3)
 KernSmooth     2.23-26  2025-01-01 [2] CRAN (R 4.4.3)
 knitr          1.50     2025-03-16 [1] CRAN (R 4.4.3)
 labeling       0.4.3    2023-08-29 [1] CRAN (R 4.4.0)
 later          1.4.2    2025-04-08 [1] CRAN (R 4.4.3)
 latex2exp      0.9.6    2022-11-28 [1] CRAN (R 4.4.3)
 lattice        0.22-6   2024-03-20 [2] CRAN (R 4.4.3)
 lifecycle      1.0.4    2023-11-07 [1] CRAN (R 4.4.3)
 lubridate    * 1.9.4    2024-12-08 [1] CRAN (R 4.4.3)
 magrittr       2.0.3    2022-03-30 [1] CRAN (R 4.4.3)
 maps           3.4.2.1  2024-11-10 [1] CRAN (R 4.4.3)
 MASS           7.3-64   2025-01-04 [2] CRAN (R 4.4.3)
 Matrix         1.7-2    2025-01-23 [2] CRAN (R 4.4.3)
 memoise        2.0.1    2021-11-26 [1] CRAN (R 4.4.3)
 mgcv           1.9-1    2023-12-21 [2] CRAN (R 4.4.3)
 mime           0.13     2025-03-17 [1] CRAN (R 4.4.3)
 miniUI         0.1.2    2025-04-17 [1] CRAN (R 4.4.3)
 munsell        0.5.1    2024-04-01 [1] CRAN (R 4.4.3)
 mvtnorm        1.3-3    2025-01-10 [1] CRAN (R 4.4.3)
 NISTunits    * 1.0.1    2016-08-11 [1] CRAN (R 4.4.0)
 nlme           3.1-167  2025-01-27 [2] CRAN (R 4.4.3)
 nnet           7.3-20   2025-01-01 [2] CRAN (R 4.4.3)
 pillar         1.10.2   2025-04-05 [1] CRAN (R 4.4.3)
 pkgbuild       1.4.7    2025-03-24 [1] CRAN (R 4.4.3)
 pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 4.4.3)
 pkgload        1.4.0    2024-06-28 [1] CRAN (R 4.4.3)
 plyr           1.8.9    2023-10-02 [1] CRAN (R 4.4.3)
 profvis        0.4.0    2024-09-20 [1] CRAN (R 4.4.3)
 proj4          1.0-15   2025-03-21 [1] CRAN (R 4.4.3)
 promises       1.3.2    2024-11-28 [1] CRAN (R 4.4.3)
 proto          1.0.0    2016-10-29 [1] CRAN (R 4.4.3)
 purrr        * 1.0.4    2025-02-05 [1] CRAN (R 4.4.3)
 R6             2.6.1    2025-02-15 [1] CRAN (R 4.4.3)
 RColorBrewer   1.1-3    2022-04-03 [1] CRAN (R 4.4.0)
 Rcpp           1.0.14   2025-01-12 [1] CRAN (R 4.4.3)
 readr        * 2.1.5    2024-01-10 [1] CRAN (R 4.4.3)
 readxl       * 1.4.5    2025-03-07 [1] CRAN (R 4.4.3)
 remotes        2.5.0    2024-03-17 [1] CRAN (R 4.4.3)
 reshape2     * 1.4.4    2020-04-09 [1] CRAN (R 4.4.3)
 rlang          1.1.5    2025-01-17 [1] CRAN (R 4.4.3)
 rmarkdown      2.29     2024-11-04 [1] CRAN (R 4.4.3)
 robustbase     0.99-4-1 2024-09-27 [1] CRAN (R 4.4.3)
 rpart          4.1.24   2025-01-07 [2] CRAN (R 4.4.3)
 rprojroot      2.0.4    2023-11-05 [1] CRAN (R 4.4.3)
 rstatix        0.7.2    2023-02-01 [1] CRAN (R 4.4.3)
 rstudioapi     0.17.1   2024-10-22 [1] CRAN (R 4.4.3)
 Rttf2pt1       1.3.12   2023-01-22 [1] CRAN (R 4.4.0)
 scales         1.3.0    2023-11-28 [1] CRAN (R 4.4.3)
 sessioninfo    1.2.3    2025-02-05 [1] CRAN (R 4.4.3)
 shiny          1.10.0   2024-12-14 [1] CRAN (R 4.4.3)
 stringi        1.8.7    2025-03-27 [1] CRAN (R 4.4.3)
 stringr      * 1.5.1    2023-11-14 [1] CRAN (R 4.4.3)
 tensorA        0.36.2.1 2023-12-13 [1] CRAN (R 4.4.0)
 tibble       * 3.2.1    2023-03-20 [1] CRAN (R 4.4.3)
 tidyr        * 1.3.1    2024-01-24 [1] CRAN (R 4.4.3)
 tidyselect     1.2.1    2024-03-11 [1] CRAN (R 4.4.3)
 tidyverse    * 2.0.0    2023-02-22 [1] CRAN (R 4.4.3)
 timechange     0.3.0    2024-01-18 [1] CRAN (R 4.4.3)
 tzdb           0.5.0    2025-03-15 [1] CRAN (R 4.4.3)
 urlchecker     1.0.1    2021-11-30 [1] CRAN (R 4.4.3)
 usethis        3.1.0    2024-11-26 [1] CRAN (R 4.4.3)
 vctrs          0.6.5    2023-12-01 [1] CRAN (R 4.4.3)
 vroom          1.6.5    2023-12-05 [1] CRAN (R 4.4.3)
 withr          3.0.2    2024-10-28 [1] CRAN (R 4.4.3)
 xfun           0.52     2025-04-02 [1] CRAN (R 4.4.3)
 xtable         1.8-4    2019-04-21 [1] CRAN (R 4.4.3)
 yaml           2.3.10   2024-07-26 [1] CRAN (R 4.4.2)

 [1] C:/Users/27086/AppData/Local/R/win-library/4.4
 [2] C:/Program Files/R/R-4.4.3/library
 * ── Packages attached to the search path.

──────────────────────────────────────────────────────────────────────────────</code></pre>
</div>
</div>
<p>The current Git commit details are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># what commit is this file at? </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="st">"git2r"</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>() <span class="sc">&amp;</span> git2r<span class="sc">::</span><span class="fu">in_repository</span>(<span class="at">path =</span> <span class="st">"."</span>)) git2r<span class="sc">::</span><span class="fu">repository</span>(here<span class="sc">::</span><span class="fu">here</span>())  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Local:    main E:/Lithic Analysis/QSYSpheroidsStudy
Remote:   main @ origin (https://github.com/zhiye0927/QSY-Spheroids-Study.git)
Head:     [b21f874] 2025-07-11: updates of conclusion</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>